#!/usr/bin/perl

# Copyright 2002-2006, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

require 5.6.1;

use strict;
use warnings;

our $VERSION = "0.57";

use blib;

use Config;
exit if $Config{useithreads};

use Devel::Cover::Test 0.57;

my @tests = @ARGV;

mkdir "test_output"       unless -d "test_output";
mkdir "test_output/cover" unless -d "test_output/cover";

unless (@tests)
{
    opendir D, "tests" or die "Cannot opendir tests: $!";
    for my $t (sort readdir D)
    {
        next unless -f "tests/$t";
        next if $t =~ /\.(pm|pl|uncoverable|version|org|bak)$/;
        next if $t =~ /~$/;

        push @tests, $t;
    }
    closedir D or die "Cannot closedir tests: $!";
}

for my $test (@tests)
{
    my $t = -e "t/$test"    ? "t/$test"    :
            -e "t/a$test.t" ? "t/a$test.t" :
            $test;
    print STDERR "creating golden results for $test\n";
    require $t or die "Can't require $t: $!";
    Devel::Cover::Test::test->create_gold;
}
