#!/usr/bin/perl

# Copyright 2004-2024, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;
use lib "tests";

use Alias1;

is_3digits(1234);
is_3digits(123);

exit;
