#!/usr/bin/perl

# Copyright 2004-2016, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

package Foo;

sub is_3digits {
    my $val = shift;
    my $retval = undef;
    $retval=1 if $val =~ /^\d{3}$/;
    return $retval;
}

package main;

*main::is_3digits = *Foo::is_3digits;
# delete $Foo::{is_3digits};

is_3digits(1234);
is_3digits(123);
