#!/usr/bin/perl

# Copyright 2013-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

my $x = 1;
my $y = 1;

if ($x && !$y) {
    die "Urgh";
}

if ($x && $y) {
}

unless ($x && $y) {
    die "Urgh";
}

if (!($x && $y)) {
    die "Urgh";
}

if (!$x || !$y) {
    die "Urgh";
}
