#!/usr/bin/perl

# Copyright 2012-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ skip_test $] < 5.032
# __COVER__ skip_reason Too fragile below 5.32

use strict;
use warnings;

use Math::BigInt ":constant";

my $x = 1;
print $x if 1 >= $x;
