#!/usr/bin/perl

# Copyright 2012-2014, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

use Math::BigInt ":constant";

my $x = 1;
print $x if 1 >= $x;
