#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ skip_test $] < 5.040
# __COVER__ skip_reason :reader not available before 5.40

use 5.40.0;
use feature "class";
no warnings "experimental::class";

class Animal {
  field $name  :param;
  field $sound :param  = "...";
  field $count :reader = 0;
  field $label :reader = "default";

  ADJUST { $name = ucfirst $name }

  method name   { $name }
  method speak  { "$name says $sound" }
  method unused { "never called" }

  method greet ($greeting = "Hello") {
    "$greeting, I am $name"
  }

  method is_loud { $sound eq "WOOF" ? 1 : 0 }

  method get_anon { method { "anon: $name" } }
}

class Dog :isa(Animal) {
  method speak      { $self->SUPER::speak . "!" }
  method unused_dog { "never called in Dog" }
}

sub main {
  my $a = Animal->new(name => "cat", sound => "meow");
  die unless $a->name eq "Cat";
  die unless $a->speak eq "Cat says meow";
  die unless $a->greet eq "Hello, I am Cat";
  die unless $a->greet("Hi") eq "Hi, I am Cat";
  die unless !$a->is_loud;
  die unless $a->count == 0;
  die unless $a->label eq "default";

  my $anon = $a->get_anon;
  die unless $a->$anon eq "anon: Cat";

  my $d = Dog->new(name => "dog", sound => "woof");
  die unless $d->speak eq "Dog says woof!";
  die unless $d->name eq "Dog";
}

main;
