#!/usr/bin/perl

# Copyright 2004-2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# test case for RT #63568 https://rt.cpan.org/Public/Bug/Display.html?id=63568

# __COVER__ skip_test $] < 5.008 || !(eval "use Test::More; 23")
# __COVER__ skip_reason Test::More not available

use Test::More;

plan tests => 1;

cmp_ok("", "eq", "");
