#!/usr/bin/perl

# Copyright 2002-2005, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my @x;

my $y  = 1;
my $z  = 0;
$::foo = 17;

for (0 .. 10)
{
  $y ||
    $x[1]++;

  $y ||
    $x[0]++ ||
    $x[1]++;

  $x[2]++
    unless $z;

  for (0 .. 2)
  {
      $x[3]++;
  }

  if ($z)
  {
    $x[4]++;
  }
  else
  {
    $x[5]++;
  }

  my $p = $y || $z;
  my $q = $z || $y;
  my $r = $_ || "qqq";
  my $s = $_ || [];
  my $t = $y | $z;
  my $u = $y || 0;
  my $v = $y || undef;

  $p     ||= $y;
  $p     ||= $z;
  $x[ 6] ||= $y;
  $x[ 7] ||= $z;
  $x[ 8] ||= 1;
  $x[ 9] ||= {};
  $x[10] ||= \"foo";
  $x[11] ||= \$y;
  $x[12] ||= \*STDIO;
  $x[13] ||= sub { 1 };
  $x[14] ||= *::foo{SCALAR};
  $x[15] ||= *STDIO{IO};
}

# print join(", ", @x), "\n";
