#!/usr/local/bin/perl

# Copyright 2002, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my @x;

my $y = 1;
my $z = 0;

for (0 .. 10)
{
  $y ||
    $x[1]++;

  $y ||
    $x[0]++ ||
    $x[1]++;

  $x[2]++
    unless $z;

  for (0 .. 2)
  {
      $x[3]++;
  }

  if ($z)
  {
    $x[4]++;
  }
  else
  {
    $x[5]++;
  }

  my $p = $y || $z;
  my $q = $z || $y;
  my $r = $_ || "qqq";
  my $s = $y | $z;

  $p ||= $y;
  $p ||= $z;
  $x[6] ||= $y;
  $x[7] ||= $z;
}

# print join(", ", @x), "\n";
