#!/usr/bin/perl

# Copyright 2002-2025, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ skip_test $] < 5.040000
# __COVER__ skip_reason ^^ not implemented

use strict;
use warnings;

sub main {
  my $i = 1;
  my $j = 0;

  for my $y (0, 1, 1, 1) {
    for my $z (0, 0, 1) {
      my $x = $y ^ $z;
      $x = $y ^^ $z;

      my $p = $i ^^ $y;
      $p = $j ^^ $y;
    }
  }
}

main
