#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# Test for overloaded objects as ternary and if/else conditions
# See GH-700

use strict;
use warnings;

my $bool_calls;

package CountBool;
use overload
  bool => sub { $bool_calls++; ${ $_[0] } },
  '""' => sub { "countbool" };
sub new { my ($class, $val) = @_; bless \$val, $class }

package main;

sub noop { }

my $true     = CountBool->new(1);
my $false    = CountBool->new(0);
my $expected = 0;

# ternary in value context, both directions
my $a = $true ? "t" : "f";
$expected++;
my $b = $false ? "t" : "f";
$expected++;

# if/else, both directions
if   ($true) { noop() }
else         { noop() }
$expected++;
if   ($false) { noop() }
else          { noop() }
$expected++;

# elsif tests its condition only when the first is false
if    ($false) { noop() }
elsif ($true)  { noop() }
else           { noop() }
$expected += 2;

# unless/else
unless ($false) { noop() }
else            { noop() }
$expected++;

# both branches empty - op_other equals op_next, no overload involved
my $p = 1;
if   ($p) { }
else      { }
my $q = 0;
if   ($q) { }
else      { }

# both branches empty with an overloaded condition - tested exactly once
if   ($true) { }
else         { }
$expected++;
if   ($false) { }
else          { }
$expected++;

# void ternary with constant legs - the same ambiguous form
$true ? 1 : 0;
$expected++;

# Extra bool calls under coverage make this branch take its true leg
print "extra bool calls\n" if $bool_calls != $expected;
