#!/usr/bin/perl

# Copyright 2002-2014, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my @x;

my $y = 1;
my $z = 0;

for (0 .. 10)
{
  $y &&
    $x[1]++;

  $y &&
    $x[0]++ &&
    $x[1]++;

  $x[2]++
    if $z;

  for (0 .. 2)
  {
      $x[3]++;
  }

  if ($y)
  {
    $x[4]++;
  }
  else
  {
    $y && $x[5]++;
  }

  my $p = $y & $z;

  $p &&= $y;
  $p &&= $z;
  my $q = 1;
  $q &&= $_;

  pas();
}

sub pas
{
    $y && $z
}

# print join(", ", @x), "\n";
