#!/usr/bin/perl

# Copyright 2004-2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

sub p
{
    my $x = shift || 11;
    my $y = shift || [];
    my $z = shift || {};
}

p $_, $_, $_ for 0, 1;
