#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# Test for Symbol::delete_package breaking pod coverage
# See GH-313

# __COVER__ criteria statement branch condition subroutine pod
# __COVER__ skip_test eval "use Pod::Coverage 0.06"; $@
# __COVER__ skip_reason Pod::Coverage unavailable

use strict;
use warnings;

use Symbol;

Symbol::delete_package("Foo");

sub bar { 1 }

bar();

package Foo;

sub foo { 2 }
