#!/usr/bin/perl -l

# Copyright 2004-2025, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

use B::Deparse;

my $xx = sub {
    print "xx";
};

print B::Deparse->new->coderef2text($xx)
