#!/usr/local/bin/perl

# Copyright 2003, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

package Destroy;

sub new { bless {}, shift }

my $x;

sub DESTROY
{
    $x++;
    $x++;
}

package main;

my $d = Destroy->new;
