#!/usr/bin/perl

# Copyright 2004-2023, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

package Destroy;

sub new { bless {}, shift }

my $x;

sub DESTROY {
    $x++;
    $x++;
}

package main;

my $d = Destroy->new;
