#!/usr/bin/perl

# Copyright 2004-2023, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use lib "tests";

$x = shift || 0;
print "1 - $x\n";
if ($x) { eval 'sub s1 { print "s1\n" }'; s1() }
print "3 - $x\n";
if ($x < 4) { eval 'sub s2 { print "s2\n" }'; s2() }
print "4 - $x\n";
if ($x < 6) { eval 'sub s3 { print "s3\n" }'; s3() }
print "5 - $x\n";
