#!/usr/bin/perl

# Copyright 2002-2004, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

use lib -d "t" ? "t" : "..";

my $x;

eval <<'EOS';
sub e
{
    $x++;
    $x
}
EOS

eval <<'EOS';
sub f
{
    $x++;
    $x
}

sub g
{
    $x++;
}

sub h
{
    $x++;
}
EOS

e();
e();
e();
f();
f();
h();
h();
h();
