#!/usr/bin/perl

# Copyright 2004-2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use lib "tests";

$x = shift || 0;
print "1 - $x\n";
if ($x) { eval 'use E2' }
print "3 - $x\n";
if ($x < 4) { eval 'use E3' }
print "4 - $x\n";
if ($x < 6) { eval 'use E4' }
print "5 - $x\n";
