#!/usr/bin/perl

# Copyright 2002-2014, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ skip_test $] == 5.010
# __COVER__ skip_reason One test fails only under make test on 5.10.0 unthreaded

use strict;
use warnings;

use lib -d "t" ? "t" : "..";

my $x;

eval <<'EOS';
sub e {
    $x++;
    $x
}
EOS

eval <<'EOS';
sub f {
    $x++;
    $x
}

sub g {
    $x++;
}

sub h {
    $x++;
}
EOS

e();
e();
e();
f();
f();
h();
h();
h();
