#!/usr/local/bin/perl

# Copyright 2002-2003, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

use lib -d "t" ? "t" : "..";

my $x;

eval <<'EOS';
sub e
{
    $x++;
    $x
}
EOS

e();
