#!/usr/bin/perl

# Copyright 2007-2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

my $pid = fork;

if ($pid)
{
    wait;
}
else
{
    local *Devel::Cover::_report = sub { die "Badness happened!" };
    exec "echo We want to be able to see this.";
}
