#!/usr/bin/perl

# Copyright 2007-2025, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

$x = 1;

exec "echo foo";

die "Unreachable";
