#!/usr/bin/perl

# Copyright 2011-2017, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ skip_test $^O eq "MSWin32"
# __COVER__ skip_reason Fork uses threads on Windows

die unless defined ($pid = fork);

if ($pid) {
    wait;
} else {
    local *Devel::Cover::_report = sub { die "Badness happened!" };
    exec "echo We want to be able to see this.";
}
