#!/usr/bin/perl

# Copyright 2004-2025, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my ($x, $p, $q, $r, $s);

$x = 0;

if ($x) {
    $p++
}

unless ($x) {
    $q++
}

$x = 1;

if ($x) {
    $r++
}

if ($x) {
    $r++
} else {
    $s++
}

unless ($x) {
    $s++
}
