#!/bin/perl

# Copyright 2002-2014, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ skip_test $] < 5.010
# __COVER__ skip_reason %+ not available before 5.10

use lib ();

BEGIN {
    lib->import(
        sub {
            print map("[$_]", @_), "\n";
            return unless $_[1] eq "IncSub.pm";
            my $fh;
            open $fh, "tests/IncSub.pm" or die $!;
            $fh
        }
    )
}

use IncSub;

BEGIN { "x" =~ /((?<x>x))/; print "$+{x}\n" }  # force Tie::Hash::NamedCapture

IncSub::check
