#!/bin/perl

use lib ();

BEGIN
{
    lib->import
    (
        sub
        {
            print map("[$_]", @_), "\n";
            return unless $_[1] eq "IncSub.pm";
            my $fh;
            open $fh, "tests/IncSub.pm" or die $!;
            $fh
        }
    )
}

use IncSub;

IncSub::check
