#!/usr/bin/perl

# Copyright 2002-2015, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

package Module1;

my $y = 7;
$y++;

sub aa {
    $y++;
}

package main;

sub xx {
  Module1::aa;
}

xx;
