#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use strict;
use warnings;

use lib "tests";

use Module_enclosing_sub;

print "named_enc:  ", Module_enclosing_sub::named_enc(20),  "\n";
print "run_anon:   ", Module_enclosing_sub::run_anon(20),   "\n";
print "nested_enc: ", Module_enclosing_sub::nested_enc(20), "\n";
print "plain:      ", Module_enclosing_sub::plain(10),      "\n";
