#!/usr/bin/perl

# Copyright 2002-2017, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ changes s/56.3/56.2/

use strict;
use warnings;

use lib "tests";

use Module2;

my @x;

sub xx {
  $x[shift]++;
  NotModule2::zz(0);
}

for (0 .. 10) {
  if (time) {
    xx(0);
  } else {
    $x[1]++;
  }
}
