#!/usr/bin/perl

# Copyright 2002-2009, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

BEGIN { push @INC, "tests" }

use Module_import;
