#!/usr/bin/perl

# Copyright 2002-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ changes s/56.3/56.2/

use strict;
use warnings;

use lib "tests";

use Module1;

my @x;

sub xx {
    $x[shift]++;
    Module1::zz(0);
}

for (0 .. 10) {
    if (time) {
        xx(0);
    } else {
        $x[1]++;
    }
}

package Module1;

my $y = 7;
$y++;

sub _aa {
    $y++;
    die;
    die;
}

sub xx {
    $y++;
    die;
}

sub yy {
    $y++;
}

sub zz {
    my $x = shift;
    $x++;
}

1

__END__

=head2 yy

yy

=cut
