#!/usr/bin/perl

# Copyright 2011-2024, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ skip_test $] < 5.010 || !(eval "use Moose; 23")
# __COVER__ skip_reason Moose not available or unreliable with Devel::Cover

package Foo;
use Moose;
__PACKAGE__->meta->make_immutable;
