#!/usr/bin/env perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use strict;
use warnings;

sub test_multiconcat {
  my ($x, $y) = ("x", 10);
  print "prefix" . $x . (defined $y ? $y : "test") . ": ";
  while () { return 10 }
}

test_multiconcat();
print "\n";
