#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use strict;
use warnings;

use Carp;

# dc noreturn usage_die

sub usage_die { die "usage\n" }
sub helper    { 1 }

sub dor_croak     { my $x = shift; my $r = $x // croak("no");       $r }
sub dor_confess   { my $x = shift; my $r = $x // confess("no");     $r }
sub dor_qualified { my $x = shift; my $r = $x // Carp::croak("no"); $r }
sub dor_ampersand { my $x = shift; my $r = $x // &croak("no");      $r }
sub dor_usage_die { my $x = shift; my $r = $x // usage_die();       $r }
sub dor_helper    { my $x = shift; my $r = $x // helper();          $r }
sub or_croak      { my $x = shift; my $r = $x || croak("no"); $r }
sub and_croak     { my $x = shift; my $r = $x && croak("no"); $r }
sub dorassign     { my $x = shift; $x //= croak("no"); $x }
sub orassign      { my $x = shift; $x ||= croak("no"); $x }

for my $sub (
  \&dor_croak,     \&dor_confess, \&dor_qualified, \&dor_ampersand,
  \&dor_usage_die, \&dor_helper,  \&or_croak,      \&and_croak,
  \&dorassign,     \&orassign,
) {
  eval { $sub->(1) };
  eval { $sub->(undef) };
}
