#!/usr/bin/env perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ criteria statement branch condition

use strict;
use warnings;

my $side_effect;

sub or_die {
  my $x = shift;
  my $v = $x or die "no value\n";
  $v
}

sub or_void {
  my $x = shift;
  $x or $side_effect = "or";
}

sub unless_modifier {
  my $x = shift;
  $side_effect = "unless" unless $x;
}

sub unless_block {
  my $x = shift;
  unless ($x) { $side_effect = "block" }
}

sub if_modifier {
  my $x = shift;
  $side_effect = "if" if $x;
}

sub and_void {
  my $x = shift;
  $x and $side_effect = "and";
}

sub dor_void {
  my $x = shift;
  $x // ($side_effect = "dor");
}

or_die($_)          for 1,     2, 3;
or_void($_)         for 0,     1, 2;
unless_modifier($_) for 0,     1, 1;
unless_block($_)    for 0,     0, 1;
if_modifier($_)     for 0,     1, 1;
and_void($_)        for 0,     1, 1;
dor_void($_)        for undef, 1, 2;
