#!/usr/bin/perl

# Copyright 2006-2018, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

package Foo;
use overload
   '""' => sub { shift->render},
   bool => sub { die; 1 };

sub render {
   "foo";
}

my $foo = 1;
bless {}, 'Foo' if $foo;

1;
