#!/usr/bin/perl

# Copyright 2014, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

{
    package Cat;

    use overload (
        'bool' => 'meh',
    );

    sub meh { 1 }
}

my $string = "hi";
my $x = bless \$string, "Cat";

my $fn = eval 'require $x';
