#!/usr/bin/perl

# Copyright 2002-2016, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ criteria pod-also_private-xx
# __COVER__ skip_test eval "use Pod::Coverage::CountParents"; $@
# __COVER__ skip_reason Pod::Coverage::CountParents unavailable

use strict;
use warnings;

use lib "tests";

use PodMod;

my @x;

sub xx {
    $x[shift]++;
    Module1::zz(0);
}

for (0 .. 10) {
    if (time) {
        xx(0);
    } else {
        $x[1]++;
    }
}
