#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# A ref to a single-statement do-block must point at the real variable, and
# a ref to a multi-statement do-block must still point at a copy.

use strict;
use warnings;

sub not_referenced { print "assignment did not reach the variable\n" }
sub not_copied     { print "multi-statement do-block was not copied\n" }

my $var;
my $foo_sr = \do { $var = undef };
$$foo_sr = "3:4:5";
not_referenced() if !defined $var || $var ne $$foo_sr;

my $multi;
my $keep;
my $multi_sr = \do { $keep = 1; $multi = undef };
$$multi_sr = "changed";
not_copied() if defined $multi;
