#!/usr/bin/perl

# Copyright 2002-2016, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use lib -d "t" ? "." : "..";
use File::Spec;
require File::Spec->catfile("tests", "E2.pm");
