#!/usr/bin/perl

# Copyright 2004-2006, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

sub main
{
    my ($debug) = @_;
    print "main\n";
    print "debug1\n" if $debug;
    if ($debug)
    {
        print "debug2\n";
    }
}

main 0;
