#!/usr/bin/perl

# Copyright 2002-2016, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my $x;

BEGIN {
    $x++
}

CHECK {
    $x++
}

INIT {
    $x++
}

END {
    $x++
}

$x++;
