#!/usr/bin/perl

# Copyright 2002-2022, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

my $pi = 3.14159; my $r  = 4;
my $c  = 2 * $pi * $r;
my $a  = $pi * $r * $r;
