#!/usr/bin/perl

# Copyright 2006-2024, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# __COVER__ test_parameters -subs_only,1

use strict;
use warnings;

use lib "tests";

my @x;

sub xx {
    $x[shift]++;
}

for (0 .. 10) {
    if (time) {
        xx(0);
    } else {
        $x[1]++;
    }
}
