#!/usr/bin/perl

# Copyright 2002-2024, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my @x;

my $y = 1;

for (0 .. 10) {
    $y &&
    $x[1]++;

    $y &&
    $x[0]++ &&
    $x[1]++;

    $x[2]++
    if $y;

    for (0 .. 2) {
        $x[3]++;
    }

    if ($y) {
        $x[4]++;
    } else {
        $x[5]++;
    }
}

# print join(", ", @x), "\n";
