#!/usr/bin/perl

# Copyright 2002-2007, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

use strict;
use warnings;

my @x;

sub xx
{
  $x[shift]++;
}

xx(4);
