#!/usr/bin/perl

# Copyright 2013-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use strict;
use warnings;
use lib "tests";

use Taint;

print "taint\n";
