#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ criteria statement subroutine pod
# __COVER__ skip_test eval "use Pod::Coverage"; $@
# __COVER__ skip_reason Pod::Coverage unavailable

use strict;
use warnings;

use lib "tests";

use Uncoverable_pod;

Uncoverable_pod::documented();
Uncoverable_pod::excused_pod();
Uncoverable_pod::stale_pod();
