#!/usr/bin/perl

# Copyright 2023-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# __COVER__ cover_parameters -ignore_covered_err

sub usub {
    # uncoverable subroutine
    # uncoverable statement
    my $x = 1;
}

sub main {
    my $x = 1;
    # uncoverable branch false
    # uncoverable branch true
    if ($x > 1) {
        $x = 0;
        # uncoverable statement
        $x = 2;
        if ($x > 3) {
            $x = 4;
        }
    }

    my $y = 0;
    # uncoverable branch true
    # uncoverable condition when:10
    if ($x > 0 && $y > 0) {
        # uncoverable statement
        $y = 1;
    }

    while ($y < 4) {
        # uncoverable branch false
        # uncoverable condition when:0X
        # uncoverable condition when:10
        if ($x > 0 && $y > 0) {
            $y = 4;
        } else {
            $y++;
        }
    }

    # uncoverable statement
    $x = 3;
    usub;
}

main
