#!/usr/bin/perl

# Copyright 2023-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# dc uncoverable subroutine class:ignore_covered_err
sub usub {
  # dc uncoverable statement  class:ignore_covered_err
    my $x = 1;
}

sub main {
    my $x = 1;
    # dc uncoverable branch false class:ignore_covered_err
    # dc uncoverable branch true
    if ($x > 1) {
        $x = 0;
        # dc uncoverable statement class:ignore_covered_err
        $x = 2;
        if ($x > 3) {
            $x = 4;
        }
    }

    my $y = 0;
    # dc uncoverable branch true
    # dc uncoverable condition when:0X
    # dc uncoverable condition when:10 class:ignore_covered_err
    # dc uncoverable condition when:11
    if ($x > 0 && $y > 0) {
        # dc uncoverable statement
        $y = 1;
    }

    while ($y < 4) {
        # dc uncoverable branch false
        # dc uncoverable condition when:0X
        # dc uncoverable condition when:10
        if ($x > 0 && $y > 0) {
            $y = 4;
        } else {
            $y++;
        }
    }

    # dc uncoverable statement class:ignore_covered_err
    $x = 3;
    usub;
}

main
