#!/usr/bin/perl

# Copyright 2004-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

my $x = 1;
my $y = 1;

# dc uncoverable branch true
# dc uncoverable condition when:0X
# dc uncoverable condition when:11

if ($x && !$y) {
  $x++;  # dc uncoverable statement
         # dc uncoverable statement
    z();
}

# dc uncoverable branch true
# dc uncoverable condition when:10
# dc uncoverable condition when:11


# an ordinary comment between the markers
  # and the code

if (!$x && $y) {
    # dc uncoverable statement count:1
    # dc uncoverable statement count:2
    b(); b();

    # dc uncoverable statement count:1,2
    b(); b();

    # dc uncoverable statement count:1..4
    b(); b(); b(); b();

    # dc uncoverable statement count:1,2,3..4,5..7,8,9,10..11,12
    b(); b(); b(); b(); b(); b(); b(); b(); b(); b(); b(); b();
}

# dc uncoverable subroutine
sub z {
  $y++;  # dc uncoverable statement
}

# dc uncoverable branch false count:1
# dc uncoverable branch true  count:2
# dc uncoverable branch false count:2
# dc uncoverable condition when:0X
# dc uncoverable condition when:10
if ($x > 0 && $y > 0) {
    $y++;
  # dc uncoverable condition when:0X
  # dc uncoverable condition when:10
  # dc uncoverable condition when:11
} elsif ($x < 2 && $y < 0) {
  $y++;  # dc uncoverable statement
} else {
  $y++;  # dc uncoverable statement
}

# dc uncoverable statement
# dc uncoverable subroutine
