# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

package Devel::Cover::Report::Html_crisp;

use 5.20.0;
use warnings;
use feature qw( postderef signatures );
no warnings qw( experimental::postderef experimental::signatures );

our $VERSION;

BEGIN {
  # VERSION
}
BEGIN { $VERSION //= $Devel::Cover::Inc::VERSION }

## no perlimports
use Devel::Cover::Html_Common     qw( $Have_highlighter highlight launch );
use Devel::Cover::Web             qw( $Cov $Crisp_base_css $Crisp_theme_js );
use Devel::Cover::Condition_table ();
use Devel::Cover::Inc             ();
use Devel::Cover::Path            qw( common_prefix );

use File::Path     qw( mkpath );
use Getopt::Long   qw( GetOptions );
use HTML::Entities qw( encode_entities );
use List::Util     qw( any );
use POSIX          qw( strftime );
our %R;
my %Assets;

my $Threshold = { c0 => 75, c1 => 90, c2 => 100 };

sub crit_name ($c) {
  qq(<span class="name-full">$R{full}{$c}</span>)
    . qq(<span class="name-short">$R{short}{$c}</span>)
}

sub render_layout (%args) {
  my $asset_prefix = $args{asset_prefix} // "";
  my $title        = $args{title} || "Coverage Report";
  my $content      = $args{content} // "";
  <<HTML
<!DOCTYPE html>
<html lang="en">
<!--
This file was generated by Devel::Cover Version $R{version}
Devel::Cover is copyright 2001-2026, Paul Johnson (paul\@pjcj.net)
Devel::Cover is free. It is licensed under the same terms as Perl itself.
The latest version of Devel::Cover should be available from my homepage:
https://pjcj.net
-->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="${asset_prefix}assets/style.css">
<link rel="icon" href="data:image/svg+xml,
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'>
<circle cx='8' cy='8' r='7' fill='$R{favicon_colour}'/>
</svg>">
<title>$title - Devel::Cover</title>
</head>
<body data-report-id="$R{report_id}" data-file-count="$R{file_count}">
$content
<div class="footer">
Generated by <a href="https://metacpan.org/pod/Devel::Cover">Devel::Cover</a>
$R{version} on $R{date} | Perl $R{perl_v} | $R{os}
</div>
<script src="${asset_prefix}assets/app.js"></script>
</body>
</html>
HTML
}

sub untested_badge () {
  my $cls = $R{have_ppi} ? "" : " tip-hover";
  my $tip = $R{have_ppi} ? "" : glass_tip("Install PPI for coverage estimates");
  qq(<span class="untested-badge$cls">untested $tip</span>)
}

sub glass_tip ($text) {
  qq(<span class="glass-tip">$text</span>)
}

sub slop_tip ($f) {
  my $cov_cls = class($f->{file_cov}, $f->{file_cov} < 100, "total");
  my $o       = <<HTML;
<div class="glass-tip slop-detail">
<dl class="slop-tip-metrics">
<dt>CC</dt><dd>$f->{file_cc}</dd>
<dt>Cov</dt><dd class="$cov_cls">$f->{file_cov}%</dd>
</dl>
HTML
  if ($f->{worst_subs}->@*) {
    $o .= qq(<dl class="slop-tip-subs">\n);
    for ($f->{worst_subs}->@*) {
      my $cls = slop_class($_->{slop});
      $o .= qq(<dt>$_->{name}</dt><dd class="$cls">$_->{crap}</dd>\n);
    }
    $o .= "</dl>\n";
  }
  $o .= <<HTML;
<div class="slop-tip-total">
<span class="slop-tip-label">CRAP</span>
<span class="slop-tip-value">$f->{file_crap}</span>
</div>
</div>
HTML
  $o
}

sub cov_bar ($pc, $uncompiled) {
  return "" if $pc eq "n/a";
  my $bar = $uncompiled ? "cov-bar-untested" : "cov-bar";
  my $fill
    = $uncompiled
    ? ""
    : qq(<span class="cov-bar-fill" style="width:${pc}%"></span>\n);
  qq(<span class="$bar">\n$fill</span>\n)
}

sub cov_cell ($s, $uncompiled, $data_value = undef) {
  my $dv = $data_value // ($s->{pc} eq "n/a" ? -1 : $s->{pc});
  <<HTML
<td class="$s->{class} tip-hover" data-value="$dv">
$s->{pc} @{[ cov_bar($s->{pc}, $uncompiled) ]}
@{[ glass_tip("$s->{covered} / $s->{total}") ]}</td>
HTML
}

sub file_row ($f, $dir) {
  my $cls = "dir-file" . ($f->{uncompiled} ? " untested" : "");
  my $name
    = $f->{exists}
    ? qq(<a href="$f->{link}">$f->{basename}</a>)
    : $f->{basename};
  my $badge = $f->{uncompiled} ? untested_badge() . "\n" : "";

  my $o = <<HTML;
<tr class="$cls" data-dir="$dir">
<td data-value="$f->{short}">$name $badge</td>
HTML

  for my $c ($R{criteria}->@*) {
    $o .= cov_cell($f->{criteria}{$c}, $f->{uncompiled});
  }
  $o .= cov_cell($f->{total}, $f->{uncompiled}, $f->{total_sort});
  $o .= <<HTML;
<td data-value="$f->{file_slop}" class="tip-hover">
$f->{file_slop} @{[ slop_tip($f) ]}</td>
</tr>
HTML
  $o
}

sub render_worst_files ($worst) {
  return "" unless @$worst && $worst->[0]{file_slop} > 0;
  my $o = qq(<div class="worst-files">\n<h2>Top SLOP</h2>\n);
  for my $f (@$worst) {
    next if $f->{file_slop} == 0;
    my $cls = $f->{uncompiled} ? "untested-worst" : $f->{total}{class};
    my $name
      = $f->{exists} ? qq(<a href="$f->{link}">$f->{short}</a>) : $f->{short};
    my $badge = $f->{uncompiled} ? untested_badge() . "\n" : "";
    my $tip   = slop_tip($f);
    my $slop  = $f->{file_slop};

    $o .= <<HTML;
<div class="worst-item $cls">
  $name $badge<strong class="tip-hover">$slop $tip</strong>
</div>
HTML
  }
  $o .= "</div>\n";
  $o
}

sub render_dist_bar ($dist) {
  my $dt = $dist->{dist_total} // 0;
  return "" unless $dt > 0;
  my $o = qq(<div class="dist-bar">\n);
  for my $seg (
    [c0       => "--cov-none-border", $dist->{tip_c0}],
    [c1       => "--cov-low-border",  $dist->{tip_c1}],
    [c2       => "--cov-good-border", $dist->{tip_c2}],
    [c3       => "--cov-full-border", $dist->{tip_c3}],
    [untested => "--untested-bar",    $dist->{tip_untested}],
  ) {
    my ($key, $var, $tip) = @$seg;
    next unless $dist->{$key};
    my $w = $dist->{$key} / $dt * 100;
    $o .= <<HTML;
<div class="dist-bar-seg tip-hover" style="width:${w}%; background:var($var)">
@{[ glass_tip($tip) ]}</div>
HTML
  }
  $o .= "</div>\n";
  my $t = $R{threshold};
  my $untested
    = $dist->{untested}
    ? qq(<span class="leg-untested">$dist->{untested} untested</span>\n)
    : "";
  $o .= <<HTML;
<div class="dist-legend">
<span class="leg-c0">$dist->{c0} &lt; $t->{c0}%</span>
<span class="leg-c1">$dist->{c1} $t->{c0}-$t->{c1}%</span>
<span class="leg-c2">$dist->{c2} $t->{c1}-100%</span>
<span class="leg-c3">$dist->{c3} at 100%</span>
$untested</div>
HTML
  $o
}

sub stat_badge ($c, $s) {
  my $pct = $s->{pc};
  my $suf = $pct ne "n/a" ? "%" : "";
  <<HTML
<span class="stat-badge $s->{class} tip-hover">
<span class="badge-label">@{[ crit_name($c) ]} $pct$suf</span>
@{[ cov_bar($pct, 0) ]}
@{[ glass_tip("$s->{covered} / $s->{total}") ]}</span>
HTML
}

sub render_index ($file_data, $total, $dist) {
  my @groups = build_dir_groups($file_data);
  my @worst
    = @$file_data
    ? (sort { $b->{file_slop} <=> $a->{file_slop} } @$file_data)
    [0 .. ($#$file_data > 4 ? 4 : $#$file_data)]
    : ();

  my $o = <<HTML;
<div class="header">
<div class="header-inner">
<h1>Coverage Report</h1>
<div class="header-stats">
HTML

  for my $c ($R{criteria}->@*) {
    next unless $total->{$c}{pc};
    $o .= stat_badge($c, $total->{$c});
  }
  my $tt = $total->{total};
  $o .= stat_badge("total", $tt) if ($tt->{pc} // "n/a") ne "n/a";

  my $ms = $R{db}->summary("Total", "slop");
  if ($ms && defined $ms->{module_slop}) {
    my $sv  = sprintf "%.1f", $ms->{module_slop};
    my $tip = sprintf "CC %d &middot; cov %.0f%% &middot; CRAP %.1f",
      $ms->{module_cc}, $ms->{module_cov}, $ms->{module_crap};
    $o .= <<HTML;
<span class="stat-badge stat-slop tip-hover">
<span class="badge-label">slop $sv</span>
@{[ glass_tip($tip) ]}</span>
HTML
  }

  $o .= <<HTML;
<button class="help-toggle" aria-label="Help">?</button>
<button class="theme-toggle" aria-label="Toggle dark mode">&#x263e;</button>
</div>
</div>
</div>

<div class="help-overlay" hidden>
<div class="help-panel">
<button class="help-close" aria-label="Close">&times;</button>
<h3>Coverage report help</h3>
<dl>
<dt>Sorting</dt>
<dd>Click any column header to sort; click again to reverse.</dd>
<dt>Filtering</dt>
<dd>Type in the filter box to filter files (supports regex).
Toggle "Hide 100% covered" to focus on incomplete files.</dd>
<dt>Grouping</dt>
<dd>Toggle "Group by directory" to organise files into
collapsible groups. Click a directory row to collapse it.</dd>
<dt>SLOP</dt>
<dd>Scaled Likelihood Of Problems - a log-scaled CRAP score
compressed to a 0-100 range. Hover for a breakdown: file CC,
combined coverage, worst subs, and the raw CRAP score.</dd>
<dt>Tooltips</dt>
<dd>Hover any badge or coverage cell for covered/total counts.</dd>
</dl>
</div>
</div>

<div class="content">
HTML

  if ($R{common_prefix}) {
    $o .= <<HTML;
<div class="common-prefix">
<span class="common-prefix-label">Prefix:</span>
<span class="common-prefix-path">$R{common_prefix}</span>
</div>
HTML
  }

  $o .= render_worst_files(\@worst);
  $o .= render_dist_bar($dist);

  $o .= <<HTML;
<div class="filter-bar">
<input type="text" class="filter-input"
  placeholder="Filter files (regex)..." aria-label="Filter files">
<label class="filter-check">
<input type="checkbox" class="hide-covered"> Hide 100% covered
</label>
<label class="filter-check">
<input type="checkbox" class="group-toggle"> Group by directory
</label>
</div>
HTML

  my $ncrit  = $R{criteria}->@*;
  my $ncols  = $ncrit + 2;       # criteria + total + slop
  my $crit_w = 70 / $ncols;
  $o
    .= qq(<table class="file-table">\n<colgroup>\n)
    . qq(<col style="width:30%">\n)
    . (qq(<col style="width:${crit_w}%">\n) x $ncols)
    . "</colgroup>\n<thead>\n<tr>\n"
    . qq(<th data-sort="file">File</th>\n);

  for my $c ($R{criteria}->@*) {
    $o .= qq(<th data-sort="$c">@{[ crit_name($c) ]}</th>\n);
  }
  $o .= <<HTML;
<th data-sort="total">@{[ crit_name('total') ]}</th>
<th data-sort="slop">SLOP</th>
</tr>
</thead>
<tbody>
HTML

  for my $g (@groups) {
    $o .= qq(<tr class="dir-header" data-dir="$g->{dir}">\n)
      . "<td>$g->{dir}</td>\n";
    for my $c ($R{criteria}->@*) {
      $o .= cov_cell($g->{criteria}{$c}, 0);
    }
    $o .= cov_cell($g->{total}, 0);
    $o .= <<HTML;
<td data-value="$g->{file_slop}" class="tip-hover">
$g->{file_slop} @{[ slop_tip($g) ]}</td>
</tr>
HTML
    $o .= file_row($_, $g->{dir}) for $g->{files}->@*;
  }
  $o .= "</tbody>\n</table>\n\n</div>\n";

  render_layout(
    asset_prefix => "",
    title        => "Coverage Summary",
    content      => $o,
  )
}

sub slop_class ($slop) {
  return "" unless defined $slop;
  $slop < 16 ? "c3" : $slop < 34 ? "c2" : $slop < 41 ? "c1" : "c0"
}

sub render_line_detail ($line) {
  my $o = qq(<tr class="line-detail"><td colspan="4">\n);

  if ($line->{subroutines}) {
    for my $s ($line->{subroutines}->@*) {
      my $status  = $s->{covered} ? "called" : "not called";
      my $cc_info = "";
      if (defined $s->{cc}) {
        my $cls  = slop_class($s->{slop});
        my $slop = sprintf "%.1f", $s->{slop} // 0;
        $cc_info = qq( <span class="$cls">CC=$s->{cc} SLOP=$slop</span>);
      }
      $o .= <<HTML;
<div class="detail">
<span class="detail-heading">Subroutine</span>
<span class="$s->{class}">$s->{name}: $status$cc_info</span>
</div>
HTML
    }
  }

  if ($line->{pod}) {
    for my $p ($line->{pod}->@*) {
      my $status = $p->{covered} ? "documented" : "undocumented";
      $o .= <<HTML;
<div class="detail">
<span class="detail-heading">Pod</span>
<span class="$p->{class}">$status</span>
</div>
HTML
    }
  }

  if ($line->{branches}) {
    my $nb = $line->{branches}->@*;
    my $pl = $nb > 1 ? "es" : "";
    $o .= <<HTML;
<div class="detail">
<span class="detail-heading">Branch: $nb branch$pl</span>
<table>
<tr><th>Branch</th><th>True</th><th>False</th><th>Total</th></tr>
HTML
    for my $b ($line->{branches}->@*) {
      $o .= <<HTML;
<tr><td>$b->{text}</td>
<td class="$b->{true_class}">$b->{true_count}</td>
<td class="$b->{false_class}">$b->{false_count}</td>
<td>$b->{total_count}</td></tr>
HTML
    }
    $o .= "</table>\n</div>\n";
  }

  if ($line->{truth_tables}) {
    for my $tt ($line->{truth_tables}->@*) {
      $o .= <<HTML;
<div class="detail">
<span class="detail-heading">Condition: $tt->{short_expr}</span>
HTML
      if ($tt->{legend} && $tt->{legend}->@*) {
        $o .= qq(<div class="tt-legend">\n);
        for my $item ($tt->{legend}->@*) {
          $o .= '<div class="tt-legend-item">'
            . qq(<strong>$item->{letter}</strong> = $item->{label}</div>\n);
        }
        $o .= "</div>\n";
      }
      $o .= "<table>\n<tr>\n";
      $o .= "<th>$_</th>" for $tt->{headers}->@*;
      $o .= "<th>result</th>\n</tr>\n";
      for my $row ($tt->{rows}->@*) {
        $o .= qq(<tr class="$row->{class}">);
        $o .= "<td>$_</td>" for $row->{inputs}->@*;
        $o .= "<td>$row->{result}</td></tr>\n";
      }
      $o .= "</table>\n</div>\n";
    }
  }

  $o .= "</td></tr>\n";
  $o
}

sub count_cell ($line, $cov_defined) {
  my $cls = "count";
  if ($line->{partial}) {
    $cls .= " exec-partial";
  } else {
    $cls .= " $line->{exec_class}" if $line->{exec_class};
    $cls .= " c0"                  if $line->{pod_uncovered};
  }
  my $aria
    = $cov_defined ? "executed $line->{count} times" : "no coverage data";
  my $count = $cov_defined ? $line->{count} : "";
  <<HTML
<td role="cell" class="$cls" aria-label="$aria">$count</td>
HTML
}

sub render_source_line ($line) {
  my $cov_defined = defined $line->{count};
  my $is_uncov
    = $cov_defined
    && $line->{count} == 0
    && ($line->{count_class} // "") eq "c0";
  my $has_detail
    = $line->{branches}
    || $line->{truth_tables}
    || $line->{subroutines}
    || $line->{pod};

  my $tr_cls = "";
  $tr_cls .= "src-c0"      if $is_uncov;
  $tr_cls .= " has-detail" if $has_detail;
  $tr_cls =~ s/\A //;

  my $o = '<tr role="row"';
  if ($cov_defined) {
    my $dcov = $line->{count} == 0 ? "0" : $line->{partial} ? "2" : "1";
    $o .= qq(\n    data-cov="$dcov");
  }
  $o .= qq(\n    class="$tr_cls")          if $tr_cls;
  $o .= qq( data-errors="$line->{errors}") if $line->{errors};
  $o .= ">\n";

  my $n = $line->{number};
  $o .= qq(<td role="cell" class="ln"><a id="L$n" href="#L$n">$n</a></td>\n);

  $o .= count_cell($line, $cov_defined);

  my $chevron = $has_detail ? "&#x25b6;" : "";
  my $src_cls = "src";
  $src_cls .= " src-c0"      if $is_uncov;
  $src_cls .= " src-partial" if $line->{partial};
  $src_cls .= " src-c1"      if ($line->{count_class} // "") eq "c1";
  my $text  = $line->{text} // "";
  $o .= qq(<td role="cell" class="chevron">$chevron</td>)
    . qq(<td role="cell" class="$src_cls">$text</td></tr>\n);

  $o .= render_line_detail($line) if $has_detail;
  $o
}

sub render_file_page ($fd, $lines, $total, $prev_file, $next_file) {
  my $o = $fd->{uncompiled} ? qq(<div class="untested-page">\n) : "";

  $o .= <<HTML;
<div class="header">
<div class="header-inner">
<h1>$fd->{short}
@{[ $fd->{uncompiled} ? untested_badge() : "" ]}</h1>
<div class="header-stats">
<span class="filter-label">filter:</span>
HTML

  for my $c ($R{criteria}->@*) {
    my $s = $total->{$c};
    if ($fd->{uncompiled}) {
      $o .= <<HTML;
<span class="stat-badge untested-stat tip-hover" data-criterion="$c">
@{[ crit_name($c) ]} 0.0% @{[ glass_tip("$c: 0") ]}</span>
HTML
    } else {
      my $cls = $s->{class} || "stat-na";
      my $pct = $s->{pc} . ($s->{pc} ne "n/a" ? "%" : "");
      $o .= <<HTML;
<span class="stat-badge $cls tip-hover" data-criterion="$c">
@{[ crit_name($c) ]} $pct @{[ glass_tip("$s->{covered} / $s->{total}") ]}</span>
HTML
    }
  }

  if ($fd->{uncompiled}) {
    $o .= <<HTML;
<span class="stat-badge untested-stat tip-hover">
@{[ crit_name("total") ]} 0.0% @{[ glass_tip("total: 0") ]}</span>
<span class="stat-badge stat-slop tip-hover">
SLOP 0 @{[ glass_tip("SLOP: 0") ]}</span>
HTML
  } else {
    my $tt = $total->{total};
    if (($tt->{pc} // "n/a") ne "n/a") {
      $o .= <<HTML;
<span class="stat-badge $tt->{class} tip-hover">
@{[ crit_name("total") ]} $tt->{pc}%
@{[ glass_tip("$tt->{covered} / $tt->{total}") ]}</span>
HTML
    }
    $o .= <<HTML;
<span class="stat-badge stat-slop tip-hover">
SLOP $fd->{file_slop} @{[ slop_tip($fd) ]}</span>
HTML
  }

  $o .= <<HTML;
<button class="help-toggle" aria-label="Help">?</button>
<button class="theme-toggle" aria-label="Toggle dark mode">&#x263e;</button>
</div>
</div>
</div>

<div class="help-overlay" hidden>
<div class="help-panel">
<button class="help-close" aria-label="Close">&times;</button>
<h3>File coverage help</h3>
<dl>
<dt>Filter badges</dt>
<dd>Click a criterion badge (stmt, bran, etc.) to expand all
lines with errors of that type. Click again to close.</dd>
<dt>Line details</dt>
<dd>Click any line with a &#x25b6; chevron to expand branch,
condition, or subroutine detail.</dd>
<dt>Minimap</dt>
<dd>The strip on the right shows coverage at a glance. Click to
jump to that line.</dd>
<dt>Tooltips</dt>
<dd>Hover badges for covered/total counts. Hover SLOP for a
breakdown.</dd>
<dt>Keyboard</dt>
<dd><kbd>j</kbd> / <kbd>k</kbd> next/prev uncovered line
(or open detail when filtered)
&middot; <kbd>Enter</kbd> toggle detail on current line
&middot; <kbd>s</kbd> <kbd>b</kbd> <kbd>c</kbd> <kbd>u</kbd>
<kbd>p</kbd> toggle filter for stmt / bran / cond / sub / pod
&middot; <kbd>[</kbd> / <kbd>]</kbd> prev/next file
&middot; <kbd>?</kbd> toggle this help</dd>
</dl>
</div>
</div>

<div class="content">
HTML

  $o .= file_nav($prev_file, $next_file);
  $o .= <<HTML;
<div class="minimap"></div>
<table class="source-table" role="table" aria-label="Coverage for $fd->{short}">
HTML

  $o .= render_source_line($_) for @$lines;
  $o .= "</table>\n";
  $o .= file_nav($prev_file, $next_file);
  $o .= "</div>\n";
  $o .= "</div>\n" if $fd->{uncompiled};

  render_layout(asset_prefix => "", title => $fd->{short}, content => $o)
}

sub file_nav ($prev_file, $next_file) {
  my $prev
    = $prev_file
    ? qq(<a href="$prev_file->{link}" class="nav-prev">)
    . "&laquo; $prev_file->{short}</a>"
    : "";
  my $next
    = $next_file
    ? qq(<a href="$next_file->{link}" class="nav-next">)
    . "$next_file->{short} &raquo;</a>"
    : "";
  <<HTML
<div class="file-nav">
<span>$prev</span>
<span><a href="$R{options}{option}{outputfile}">&uarr; Summary</a></span>
<span>$next</span>
</div>
HTML
}

sub class ($pc, $err, $criterion) {
  return "" if $criterion && $criterion eq "time";
  return "na" unless defined $pc && $pc =~ /\A[0-9.]+\z/;
  no warnings "uninitialized";
     !$err                   ? "c3"
    : $pc < $Threshold->{c0} ? "c0"
    : $pc < $Threshold->{c1} ? "c1"
    : $pc < $Threshold->{c2} ? "c2"
    :                          "c3"
}

sub oclass ($o, $criterion) {
  $o ? class($o->percentage, $o->error, $criterion) : ""
}

sub fmt_pc ($pc) {
  defined $pc
    ? (sprintf "%5.2f", $pc) =~ s/.\z//r =~ s/^\s+//r =~ s/^100\.0$/100/r
    : "n/a"
}

sub _format_criterion ($part, $criterion) {
  return { pc => "n/a", class => "na", covered => 0, total => 0, error => 0 }
    unless $part && exists $part->{$criterion};
  my $c = $part->{$criterion};
  {
    pc      => fmt_pc($c->{percentage}),
    class   => class($c->{percentage}, $c->{error}, $criterion),
    covered => $c->{covered} || 0,
    total   => $c->{total}   || 0,
    error   => $c->{error}   || 0,
  }
}

sub get_summary ($file, $criterion) {
  _format_criterion($R{db}->summary($file), $criterion)
}

sub _apply_slop ($f, $slop_data) {
  if ($slop_data && defined $slop_data->{file_crap}) {
    $f->{file_crap} = sprintf "%.1f", $slop_data->{file_crap};
    $f->{file_slop} = sprintf "%.1f", $slop_data->{file_slop} // 0;
    $f->{file_cc}   = $slop_data->{file_cc};
    $f->{file_cov}  = sprintf "%.0f", $slop_data->{file_cov};
    my @sorted = sort { $b->{crap} <=> $a->{crap} } grep defined $_->{crap},
      @{ $slop_data->{subs} || [] };
    $f->{worst_subs} = [
      map { {
        name => $_->{name},
        crap => sprintf("%.1f", $_->{crap}),
        slop => $_->{slop},
      } } @sorted[0 .. ($#sorted > 2 ? 2 : $#sorted)]
    ];
  } else {
    $f->{file_crap}  = 0;
    $f->{file_slop}  = 0;
    $f->{file_cc}    = 0;
    $f->{file_cov}   = 0;
    $f->{worst_subs} = [];
  }
}

sub build_one_file ($file) {
  return unless $R{db}->summary($file);
  my $dir = $file =~ s|/[^/]+$||r;
  $dir = "" if $dir eq $file;
  my $basename   = $file =~ s|.*/||r;
  my $meta       = $R{db}->cover->file($file)->{meta} // {};
  my $uncompiled = $meta->{uncompiled} ? 1 : 0;
  my %f          = (
    name       => $file,
    basename   => $basename,
    dir        => $dir,
    link       => "$R{filenames}{$file}.html",
    exists     => -e $file,
    uncompiled => $uncompiled,
    criteria   => {},
  );

  for my $c ($R{showing}->@*) {
    my $s = get_summary($file, $c);
    $s->{class}      = "c0"  if $uncompiled && $s->{pc} eq "n/a";
    $s->{pc}         = "0.0" if $uncompiled && $s->{pc} eq "n/a";
    $f{criteria}{$c} = $s;
  }
  my $total = get_summary($file, "total");
  if ($uncompiled && $total->{pc} eq "n/a") {
    $total->{class} = "c0";
    $total->{pc}    = "0.0";
  }
  $f{total} = $total;
  my $pc = $total->{pc} // "n/a";
  $f{total_pc}   = $pc;
  $f{total_sort} = $pc eq "n/a" ? -1 : $pc;
  _apply_slop(\%f, $R{db}->summary($file, "slop"));
  \%f
}

sub build_file_data () {
  my @file_data;
  for my $file ($R{options}{file}->@*) {
    my $f = build_one_file($file);
    push @file_data, $f if $f;
  } sort {
         ($b->{file_slop} || 0)   <=> ($a->{file_slop} || 0)
      || ($a->{total_sort} // -1) <=> ($b->{total_sort} // -1)
      || $a->{name} cmp $b->{name}
  } @file_data
}

sub get_dir_summary ($dir, $criterion) {
  _format_criterion($R{db}->dir_summary($dir), $criterion)
}

sub build_dir_groups ($file_data) {
  my %dirs;
  push $dirs{ $_->{dir} }->@*, $_ for @$file_data;
  map {
    my $dir = $_;
    my $g   = {
      dir      => $dir || "(root)",
      dir_key  => $dir,
      total    => get_dir_summary($dir, "total"),
      criteria =>
        { map { $_ => get_dir_summary($dir, $_) } $R{criteria}->@* },
      files => $dirs{$dir},
    };
    $g->{pc}    = $g->{total}{pc};
    $g->{class} = $g->{total}{class};
    _apply_slop($g, $R{db}->dir_summary($dir, "slop"));
    $g;
  } sort keys %dirs
}

sub line_subroutines ($f, $n) {
  my $subs = $f->subroutine or return;
  my $loc  = $subs->location($n);
  return unless $loc && @$loc;
  my $cl = $R{slop_subs} || {};
  map { {
    name    => encode_entities($_->name),
    covered => $_->covered,
    class   => oclass($_, "subroutine"),
    cc      => ($cl->{ "$n\0" . $_->name } // {})->{cc},
    crap    => ($cl->{ "$n\0" . $_->name } // {})->{crap},
    slop    => ($cl->{ "$n\0" . $_->name } // {})->{slop},
  } } @$loc
}

sub line_pod ($f, $n) {
  my $pod = $f->pod or return;
  my $loc = $pod->location($n);
  return unless $loc && @$loc;
  map { { covered => $_->covered, class => oclass($_, "pod") } } @$loc
}

sub line_branches ($f, $n) {
  my $branches = $f->branch or return;
  my $loc      = $branches->location($n);
  return unless $loc && @$loc;
  map {
    my $t = $_->value(0);
    my $f = $_->value(1);
    {
      true_count  => $t,
      false_count => $f,
      total_count => $t + $f,
      true_class  => class($t, $_->error(0), "branch"),
      false_class => class($f, $_->error(1), "branch"),
      text        => encode_entities($_->text // ""),
    }
  } @$loc
}

sub line_truth_tables ($f, $n) {
  my $conditions = $f->condition or return;
  my $loc        = $conditions->location($n);
  return unless $loc && @$loc;
  grep { $_->{rows}->@* } map {
    my @rows = map { {
      inputs  => $_->inputs,
      result  => $_->result,
      covered => $_->covered,
      class   => $_->covered ? "c3" : "c0",
    } } $_->rows;
    my @labels  = $_->labels;
    my @headers = map { chr ord("A") + $_ } 0 .. $#labels;
    {
      expr       => encode_entities($_->expr),
      short_expr => encode_entities($_->short_expr),
      rows       => \@rows,
      headers    => \@headers,
      legend     => [
        map { {
          letter => $headers[$_], label => encode_entities($labels[$_]) } }
          0 .. $#labels
      ],
    }
  } Devel::Cover::Condition_table->for_line($loc)
}

sub exec_class ($count) {
  defined $count && $count > 0 ? "exec-covered" : "exec-0"
}

sub line_statement ($f, $n, $line) {
  my $stmt = $f->statement or return;
  my $loc  = $stmt->location($n);
  return unless $loc && @$loc;
  my $s = $loc->[0];
  $line->{count}       = $s->covered;
  $line->{count_class} = oclass($s, "statement");
  $line->{exec_class}  = exec_class($s->covered);
}

sub line_partial ($line, $bd, $tts, $sd) {
  return unless defined $line->{count} && $line->{count} > 0;
  my $p;
  $p ||= any { $_->{true_count} == 0 || $_->{false_count} == 0 } @$bd;
  $p ||= any { any { !$_->{covered} } $_->{rows}->@* } @$tts;
  $p ||= any { !$_->{covered} } @$sd;
  $p ||= $line->{pod_uncovered};
  $line->{partial} = 1 if $p;
}

sub read_source ($file) {
  open my $fh, "<", $file or warn("Unable to open $file: $!\n"), return;
  my @all_lines = <$fh>;
  close $fh or die "Can't close $file: $!\n";

  if ($Have_highlighter) {
    my @hl = highlight($R{options}{option}, @all_lines);
    @all_lines = @hl if @hl;
  }
  @all_lines
}

sub build_source_lines ($file) {
  my $f = $R{db}->cover->file($file);

  my @all_lines = read_source($file) or return [];

  my @lines;
  my $n = 0;
  for my $l (@all_lines) {
    $n++;
    chomp $l;

    my %line = (number => $n, text => length $l ? $l : "&nbsp;");

    line_statement($f, $n, \%line);

    my @bd = line_branches($f, $n);
    $line{branches} = \@bd if @bd;

    my @tts = line_truth_tables($f, $n);
    $line{truth_tables} = \@tts if @tts;

    my @sd = line_subroutines($f, $n);
    $line{subroutines} = \@sd if @sd;

    my @pd = line_pod($f, $n);
    if (@pd) {
      $line{pod}           = \@pd;
      $line{pod_uncovered} = 1 if any { !$_->{covered} } @pd;
    }

    line_partial(\%line, \@bd, \@tts, \@sd);

    my @errors;
    push @errors, "branch"
      if any { $_->{true_count} == 0 || $_->{false_count} == 0 } @bd;
    push @errors, "condition" if any {
      any { !$_->{covered} }
        $_->{rows}->@*
    } @tts;
    push @errors, "subroutine" if any { !$_->{covered} } @sd;
    push @errors, "pod"        if $line{pod_uncovered};
    $line{errors} = join ",", @errors if @errors;

    push @lines, \%line;
    last if $l =~ /^__(END|DATA)__/;
  }

  \@lines
}

sub build_untested_source_lines ($file) {
  my @all_lines = read_source($file) or return [];

  my @lines;
  my $n = 0;
  for my $l (@all_lines) {
    $n++;
    chomp $l;
    my %line = (number => $n, text => length $l ? $l : "&nbsp;");
    push @lines, \%line;
    last if $l =~ /^__(END|DATA)__/;
  }

  \@lines
}

sub write_file ($path, $content) {
  open my $fh, ">", $path or die "Can't open $path: $!\n";
  print $fh $content;
  close $fh or die "Can't close $path: $!\n";
}

sub get_options ($self, $opt) {
  $opt->{option}{outputfile} = "coverage.html";
  $opt->{option}{restrict}   = 1;
  $Threshold->{$_}           = $opt->{"report_$_"}
    for grep { defined $opt->{"report_$_"} } qw( c0 c1 c2 );
  die "Invalid command line options"
    unless GetOptions($opt->{option}, qw( noppihtml noperltidy outputfile=s ));
}

sub favicon ($level) {
  state $map = { c0 => "none", c1 => "low", c2 => "good", c3 => "full" };
  $Cov->{light}{ $map->{$level} // "full" }{border} =~ s/^#/%23/r
}

sub set_favicon_colour () {
  my $t  = get_summary("Total", "total");
  my $pc = $t->{pc};
  $pc = 0 if !defined $pc || $pc eq "n/a";
  my $cl = class($pc, $pc < 100 ? 1 : 0, "total");
  $R{favicon_colour} = favicon($cl);
}

sub totals_for ($file) {
  my %total;
  for my $c ($R{showing}->@*) {
    $total{$c} = get_summary($file, $c);
  }
  $total{total} = get_summary($file, "total");
  %total
}

sub coverage_distribution ($file_data) {
  my %dist = (c0 => 0, c1 => 0, c2 => 0, c3 => 0, untested => 0);
  for my $fd (@$file_data) {
    if ($fd->{uncompiled}) {
      $dist{untested}++;
    } else {
      my $cl = $fd->{total}{class} || "c3";
      $dist{$cl}++ if exists $dist{$cl};
    }
  }
  $dist{dist_total} = @$file_data || 1;

  my $pl = sub ($n) { $n == 1 ? "file" : "files" };
  my $t  = $Threshold;
  $dist{tip_c0} = "$dist{c0} ${\$pl->($dist{c0})}" . " &lt; $t->{c0}%";
  $dist{tip_c1} = "$dist{c1} ${\$pl->($dist{c1})}" . " $t->{c0}-$t->{c1}%";
  $dist{tip_c2} = "$dist{c2} ${\$pl->($dist{c2})}" . " $t->{c1}-100%";
  $dist{tip_c3} = "$dist{c3} ${\$pl->($dist{c3})}" . " 100%";
  $dist{tip_untested} = "$dist{untested} untested ${\$pl->($dist{untested})}";
  %dist
}

sub generate_index ($outdir, $options, $file_data, $total, $dist) {
  my $html = "$outdir/$options->{option}{outputfile}";
  write_file($html, render_index($file_data, $total, $dist));
}

sub generate_file_pages ($outdir, $file_data) {
  for my $idx (0 .. $#$file_data) {
    my $fd = $file_data->[$idx];
    next unless $fd->{exists};
    my $file = $fd->{name};
    $R{slop_subs} = $R{db}->slop_sub_lookup($file);
    my $lines
      = $fd->{uncompiled}
      ? build_untested_source_lines($file)
      : build_source_lines($file);
    my %file_total = $fd->{uncompiled}
      ? (
        map { $_ => $fd->{criteria}{$_} // $fd->{total} } $R{showing}->@*,
        "total",
      )
      : totals_for($file);

    my $prev = $idx > 0            ? $file_data->[$idx - 1] : undef;
    my $next = $idx < $#$file_data ? $file_data->[$idx + 1] : undef;

    write_file(
      "$outdir/$fd->{link}",
      render_file_page($fd, $lines, \%file_total, $prev, $next),
    );
    delete $R{slop_subs};
  }
}

sub report ($pkg, $db, $options) {
  my $fname = (sort keys $db->{runs}->%*)[0] or return;
  my $run   = $db->{runs}{$fname};

  %R = (
    module   => { name => $run->name, version => $run->version },
    db       => $db,
    date     => strftime("%Y-%m-%d %H:%M:%S %z", localtime),
    perl_v   => $^V,
    os       => $^O,
    options  => $options,
    version  => $VERSION,
    showing  => [grep $options->{show}{$_}, $db->criteria],
    criteria => [grep $_ ne "time", grep $options->{show}{$_}, $db->criteria],
    headers  => [
      map  { ($db->criteria_short)[$_] }
      grep { $options->{show}{ ($db->criteria)[$_] } }
        (0 .. $db->criteria - 1)
    ],
    short => do {
      my @c = $db->criteria;
      my @s = $db->criteria_short;
      +{ (map { $c[$_] => $s[$_] } 0 .. $#c), total => "total" }
    },
    full => do {
      my @c = $db->criteria;
      +{ (map { $_ => ucfirst } @c), total => "total" }
    },
    filenames => {
      map { $_ => do { (my $f = $_) =~ s/\W/-/g; $f } } $options->{file}->@*
    },
    threshold      => $Threshold,
    have_ppi       => eval { require PPI; 1 } ? 1 : 0,
    favicon_colour => favicon("c3"),
    report_id      => $options->{outputdir},
    file_count     => 0 + $options->{file}->@*,
  );

  set_favicon_colour;

  my $outdir = $options->{outputdir};
  my $assets = "$outdir/assets";
  mkpath($assets) unless -d $assets;

  write_file("$assets/style.css", $Assets{css});
  write_file("$assets/app.js",    $Assets{js});

  my @file_data = build_file_data;

  my ($prefix, $short_map) = common_prefix(map { $_->{name} } @file_data);
  $R{common_prefix} = $prefix;
  if ($prefix) {
    for my $f (@file_data) {
      my $s = $short_map->{ $f->{name} };
      $f->{short} = $s;
      (my $dir = $s) =~ s{/[^/]+$}{};
      $dir           = "" if $dir eq $s;
      $f->{dir}      = $dir;
      $f->{basename} = $s =~ s{.*/}{}r;
    }
  } else {
    $_->{short} = $_->{name} for @file_data;
  }

  my %total = totals_for("Total");
  my %dist  = coverage_distribution(\@file_data);

  generate_index($outdir, $options, \@file_data, \%total, \%dist);
  generate_file_pages($outdir, \@file_data);

  my $html = "$outdir/$options->{option}{outputfile}";
  print "HTML output written to $html\n" unless $options->{silent};
}

$Assets{css} = $Crisp_base_css . <<'CSS';
/* Devel::Cover Html_crisp report - page-specific styles */

.header-inner {
  container-type: inline-size;
}

.stat-badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: var(--font-size-small);
  font-variant-numeric: tabular-nums;
  padding: 2px 8px;
  border-radius: 4px;
  border: 1px solid;
  transition: opacity 0.15s ease;
  white-space: nowrap;
  width: 180px;
}

.badge-label {
  flex: 1;
  min-width: 0;
}

.stat-badge .cov-bar {
  flex-shrink: 0;
}

/* Table headers: switch to short names when columns get narrow */
@media (max-width: 920px) {
  .file-table .name-full  { display: none; }
  .file-table .name-short { display: inline; }
}

/* Medium: switch to short criterion names, narrower badges */
@container (max-width: 1450px) {
  .name-full  { display: none !important; }
  .name-short { display: inline !important; }
  .stat-badge { width: 140px; }
  .stat-slop  { width: auto; }
}

/* Narrow: stack pills vertically */
@container (max-width: 1200px) {
  .header-stats {
    flex-direction: column;
    align-items: flex-end;
    gap: 4px;
  }
}

.stat-badge:hover { opacity: 0.85; }
.stat-na {
  background: var(--bg-alt);
  border-color: var(--border);
  color: var(--fg-muted);
}
.stat-slop {
  background: var(--prefix-bg);
  border-color: var(--prefix-border);
  color: var(--fg);
  width: auto;
}
.stat-badge[data-criterion] {
  cursor: pointer;
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}
.stat-badge[data-criterion]:hover {
  transform: translateY(-1px);
  box-shadow: 0 2px 4px rgba(0,0,0,0.15);
  opacity: 1;
}
.stat-badge.badge-active {
  outline: 2px solid var(--link);
  outline-offset: -1px;
}
.filter-label {
  font-size: 11px;
  color: var(--fg-muted);
  font-weight: 600;
  letter-spacing: 0.03em;
  text-transform: uppercase;
}

.help-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.5);
  z-index: 100;
  display: none;
  align-items: center;
  justify-content: center;
}

.help-overlay:not([hidden]) {
  display: flex;
}

.help-panel {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 24px 32px;
  max-width: 520px;
  width: 90%;
  max-height: 80vh;
  overflow-y: auto;
  box-shadow: 0 8px 32px rgba(0,0,0,0.3);
}

.help-panel h3 {
  margin: 0 0 12px 0;
  font-size: 16px;
}

.help-panel dt {
  font-weight: 600;
  font-size: var(--font-size-small);
  margin-top: 10px;
}

.help-panel dd {
  margin: 2px 0 0 0;
  font-size: var(--font-size-small);
  color: var(--fg-muted);
}

.help-panel kbd {
  display: inline-block;
  padding: 1px 5px;
  border: 1px solid var(--border);
  border-radius: 3px;
  background: var(--header-bg);
  font-family: var(--font-code);
  font-size: 11px;
}

.help-panel .help-close {
  float: right;
  background: none;
  border: none;
  font-size: 18px;
  cursor: pointer;
  color: var(--fg-muted);
  padding: 0;
  line-height: 1;
}

.help-panel .help-close:hover { color: var(--fg); }

/* Common prefix */

.common-prefix {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  background: var(--prefix-bg);
  border: 1px solid var(--prefix-border);
  border-radius: 6px;
  padding: 6px 14px;
  margin: 16px 0;
  font-size: var(--font-size-small);
}

.common-prefix-label {
  color: var(--prefix-label);
  font-weight: 600;
}

.common-prefix-path {
  font-family: monospace;
  color: var(--fg);
}

/* Worst files */

.worst-files {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  overflow: hidden;
  margin-bottom: 24px;
}

.worst-files h2 {
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  margin: 0;
  color: var(--fg-muted);
}

.worst-item {
  padding: 6px 12px;
  border-radius: 4px;
  border: 1px solid;
  font-size: var(--font-size-small);
  transition: opacity 0.15s ease;
}

.worst-item:hover { opacity: 0.85; }

.worst-item a { color: inherit; }

/* Filter bar */

.filter-bar {
  display: flex;
  gap: 16px;
  align-items: center;
  margin-bottom: 12px;
  flex-wrap: wrap;
}

.filter-input {
  padding: 4px 10px;
  border: 1px solid var(--border);
  border-radius: 4px;
  font-size: var(--font-size-small);
  background: var(--bg);
  color: var(--fg);
  min-width: 200px;
  transition: border-color 0.15s ease, outline 0.15s ease;
}

.filter-input:focus {
  outline: 2px solid var(--link);
  outline-offset: -1px;
}

.filter-check {
  font-size: var(--font-size-small);
  color: var(--fg-muted);
  cursor: pointer;
  user-select: none;
  display: flex;
  align-items: center;
  gap: 4px;
}

/* File table */

.file-table {
  width: 100%;
  border-collapse: collapse;
  font-size: var(--font-size-small);
  table-layout: fixed;
}

.file-table th {
  background: var(--header-bg);
  border: 1px solid var(--border);
  padding: 6px 10px;
  text-align: center;
  font-weight: 600;
  cursor: pointer;
  user-select: none;
  overflow: hidden;
  text-overflow: ellipsis;
}

.file-table th:first-child { text-align: left; }
.file-table th:hover { background: var(--border); }

.file-table td {
  border: 1px solid var(--border);
  padding: 4px 10px;
  text-align: center;
  white-space: nowrap;
}

@media (max-width: 1150px) {
  .file-table td { white-space: normal; }
  .file-table .cov-bar {
    display: block;
    width: 100%;
    margin-left: 0;
    margin-top: 2px;
  }
}

.file-table td:first-child { text-align: left; }

.file-table tr { transition: background 0.15s ease; }
.file-table tr:hover { background: var(--bg-alt); }

.file-table .sort-asc::after { content: " \25b2"; }
.file-table .sort-desc::after { content: " \25bc"; }

/* SLOP detail tooltip overrides */
.glass-tip.slop-detail {
  padding: 8px 12px;
  font-weight: normal;
}

.slop-detail dl {
  display: grid;
  grid-template-columns: auto auto;
  gap: 1px 12px;
  margin: 0;
  font-variant-numeric: tabular-nums;
}
.slop-detail dt { text-align: left; }
.slop-detail dd { text-align: right; margin: 0; }

.slop-tip-subs {
  border-top: 1px solid var(--tip-glass-sep);
  margin-top: 4px !important;
  padding-top: 4px;
}

.slop-tip-total {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  border-top: 1px solid var(--tip-glass-sep);
  margin-top: 4px;
  padding-top: 4px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}

.slop-detail .c0,
.slop-detail .c1,
.slop-detail .c2,
.slop-detail .c3 { background: transparent; }
.slop-detail .c0 { color: var(--tip-c0); }
.slop-detail .c1 { color: var(--tip-c1); }
.slop-detail .c2 { color: var(--tip-c2); }
.slop-detail .c3 { color: var(--tip-c3); }

/* Header: tooltips below */
.header .glass-tip {
  bottom: auto;
  top: 100%;
  margin-top: 4px;
}

.dir-header {
  cursor: pointer;
  user-select: none;
}

.dir-header td {
  background: var(--bg-alt);
  border-top: 6px solid var(--bg);
  font-weight: 600;
}

.dir-header td:first-child {
  color: var(--fg-muted);
}

.dir-header td:first-child::before {
  content: "\25be ";
  font-size: 10px;
}

.dir-header.collapsed td:first-child::before {
  content: "\25b8 ";
}

.dir-file-grouped td:first-child {
  padding-left: 24px !important;
}

/* Untested files */

tr.untested td { opacity: 0.7; }
tr.untested td .glass-tip { display: none !important; }
tr.untested td:hover { opacity: 1; }
tr.untested td:hover .tip-hover:hover > .glass-tip {
  display: block !important;
}

.cov-bar-untested {
  display: inline-block;
  width: 50px;
  height: 8px;
  background: var(--untested-bar);
  border-radius: 4px;
  vertical-align: middle;
  margin-left: 4px;
  overflow: hidden;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.15);
}

tr.untested td:first-child,
tr.dir-file td:first-child {
  display: flex;
  align-items: center;
}
tr.untested td:first-child a,
tr.untested td:first-child span:first-child,
tr.dir-file td:first-child a {
  flex: 1;
}
.untested-badge {
  display: inline-block;
  font-size: 10px;
  padding: 1px 5px;
  border-radius: 3px;
  margin-left: 6px;
  flex-shrink: 0;
  font-weight: 600;
  letter-spacing: 0.03em;
  background: var(--untested-badge-bg);
  color: var(--untested-badge-fg);
  border: 1px solid var(--untested-badge-border);
}

.untested-worst {
  background: var(--untested-worst-bg);
  border-color: var(--untested-bar);
  color: var(--untested-worst-fg);
}

.untested-stat {
  background: var(--untested-worst-bg);
  border-color: var(--untested-bar);
  color: var(--untested-worst-fg);
}

.untested-page .source-table { opacity: 0.7; }
.untested-page .exec-0 { background: var(--untested-bar); }

/* Source view */

.source-table {
  width: 100%;
  border-collapse: collapse;
  font-family: var(--font-code);
  font-size: var(--font-size-code);
  line-height: 1.4;
}

.source-table td {
  padding: 0 2px;
  border: none;
  vertical-align: top;
  line-height: 1.3;
}

.source-table tr { transition: background 0.15s ease; }
.source-table tr:hover { background: var(--bg-alt); }

.ln {
  width: 1px;
  text-align: right;
  color: var(--fg-muted);
  user-select: none;
  padding-right: 8px !important;
  border-right: 1px solid var(--border);
}

.ln a { color: var(--fg-muted); }
.ln a:hover { color: var(--link); }

.count {
  width: 1px;
  text-align: right;
  padding: 0 8px !important;
  font-size: var(--font-size-small);
}

.exec-0 { background: var(--exec-none); }
.exec-partial { background: var(--exec-partial); }
.exec-covered { background: var(--exec-covered); }

.src {
  white-space: pre;
  border-left: 3px solid transparent;
  padding-left: 8px !important;
}

.src-c0 {
  border-left-color: var(--cov-none-border);
}
.src-c1 {
  border-left-color: var(--cov-low-border);
  background: var(--cov-low-bg);
}

.src-partial {
  border-left-color: var(--cov-good-border);
}

td.chevron {
  width: 1px;
  padding: 0 2px !important;
  font-size: 8px;
  color: var(--fg-muted);
}

/* Syntax highlighting (PPI::HTML) */

.comment { color: var(--syn-comment); font-style: italic; }
.keyword { color: var(--syn-keyword); }
.double, .single, .heredoc, .heredoc_content,
  .heredoc_terminator { color: var(--syn-string); }
.number { color: var(--syn-number); }
.symbol, .cast { color: var(--syn-symbol); }
.operator { color: var(--syn-operator); }
.structure { color: var(--syn-structure); }
.core { color: var(--syn-core); }
.pragma { color: var(--syn-pragma); }
.magic { color: var(--syn-magic); }
.word { color: var(--fg); }

/* Inline detail sections */

.has-detail { cursor: pointer; }
.has-detail:hover { background: var(--bg-alt); }

.detail {
  background: var(--bg-alt);
  border: 1px solid var(--border);
  border-radius: 4px;
  margin: 4px 0 4px 40px;
  padding: 8px 12px;
  font-family: var(--font-code);
  font-size: var(--font-size-small);
}

.detail-heading {
  font-weight: 600;
  color: var(--fg-muted);
}

.detail table {
  border-collapse: collapse;
  margin-top: 4px;
}

.detail th, .detail td {
  border: 1px solid var(--border);
  padding: 2px 8px;
  text-align: center;
  font-size: var(--font-size-small);
}

.detail th { background: var(--header-bg); }
.detail .c0 { background: var(--exec-none); }
.detail .c3 { background: var(--exec-covered); }

.tt-legend {
  margin: 4px 0;
  font-size: var(--font-size-small);
  color: var(--fg-muted);
}

/* Minimap */

.minimap {
  position: fixed;
  right: 0;
  top: 60px;
  bottom: 40px;
  width: 14px;
  z-index: 5;
  background: var(--bg-alt);
  border-left: 1px solid var(--border);
}

.minimap canvas { display: block; }

/* Distribution bar */

.dist-bar {
  display: flex;
  height: 12px;
  border-radius: 3px;
  margin-bottom: 16px;
  border: 1px solid var(--border);
}

.dist-bar-seg {
  height: 100%;
  position: relative;
}

.dist-bar-seg:first-child { border-radius: 3px 0 0 3px; }
.dist-bar-seg:last-child { border-radius: 0 3px 3px 0; }
.dist-bar-seg:only-child { border-radius: 3px; }

.dist-bar-seg:hover { opacity: 0.8; }

.dist-legend {
  display: flex;
  gap: 12px;
  margin-bottom: 16px;
  font-size: var(--font-size-small);
  color: var(--fg-muted);
}

.dist-legend span::before {
  content: "";
  display: inline-block;
  width: 10px;
  height: 10px;
  border-radius: 2px;
  margin-right: 4px;
  vertical-align: middle;
}

.dist-legend .leg-c0::before { background: var(--cov-none-border); }
.dist-legend .leg-c1::before { background: var(--cov-low-border); }
.dist-legend .leg-c2::before { background: var(--cov-good-border); }
.dist-legend .leg-c3::before { background: var(--cov-full-border); }
.dist-legend .leg-untested::before { background: var(--untested-bar); }

/* Nav links */

.file-nav {
  display: flex;
  justify-content: space-between;
  padding: 8px 0;
  font-size: var(--font-size-small);
}

.file-nav > span {
  flex: 1;
}

.file-nav > span:nth-child(2) {
  text-align: center;
}

.file-nav > span:last-child {
  text-align: right;
}

/* Footer */

CSS

$Assets{js} = $Crisp_theme_js . <<'JS';
/* Devel::Cover Html_crisp report - progressive enhancement */
(function() {
  "use strict";

  /* Per-report localStorage helpers */
  var body = document.body;
  var rid = body.getAttribute("data-report-id") || "";
  var fileCount = parseInt(body.getAttribute("data-file-count") || "0", 10);

  function rget(key, fallback) {
    var v = localStorage.getItem("dc:" + rid + ":" + key);
    return v !== null ? v : fallback;
  }
  function rset(key, val) {
    localStorage.setItem("dc:" + rid + ":" + key, val);
  }

  /* Help overlay */
  var helpOverlay = document.querySelector(".help-overlay");
  var helpBtn = document.querySelector(".help-toggle");
  if (helpOverlay) {
    function showHelp()  { helpOverlay.hidden = false; }
    function hideHelp()  { helpOverlay.hidden = true; }
    if (helpBtn) helpBtn.addEventListener("click", function() {
      if (helpOverlay.hidden) showHelp(); else hideHelp();
    });
    helpOverlay.addEventListener("click", function(e) {
      if (e.target === helpOverlay) hideHelp();
    });
    var closeBtn = helpOverlay.querySelector(".help-close");
    if (closeBtn) closeBtn.addEventListener("click", function(e) {
      e.stopPropagation();
      hideHelp();
    });
    document.addEventListener("keydown", function(e) {
      var tag = e.target.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA") return;
      if (e.key === "Escape" && !helpOverlay.hidden) hideHelp();
      else if (e.key === "?" && helpOverlay.hidden) showHelp();
    });
  }

  /* Index page table (sort, filter, group) */
  var table = document.querySelector(".file-table");
  if (table) {
    var headers = table.querySelectorAll("th[data-sort]");
    var tbody = table.querySelector("tbody");
    var filterInput = document.querySelector(".filter-input");
    var hideCovered = document.querySelector(".hide-covered");
    var groupToggle = document.querySelector(".group-toggle");

    /* Read persisted state */
    var sortCol = rget("sort-col", "slop");
    if (sortCol === "crap") { sortCol = "slop"; rset("sort-col", "slop"); }
    var sortDir = rget("sort-dir", "desc");

    var defaultGrouped = fileCount > 30;
    var storedGrouped = rget("grouped", null);
    var isGrouped = storedGrouped !== null
      ? storedGrouped === "true"
      : defaultGrouped;

    if (filterInput)
      filterInput.value = rget("filter", "");
    if (hideCovered)
      hideCovered.checked = rget("hide-covered", "false") === "true";
    if (groupToggle)
      groupToggle.checked = isGrouped;

    /* Render: applies grouping, sort, filter in order */
    function render() {
      var grouped = groupToggle && groupToggle.checked;
      var filterText = filterInput ? filterInput.value : "";
      var hide = hideCovered ? hideCovered.checked : false;
      var re;
      try { re = new RegExp(filterText, "i"); }
      catch(e) { re = null; }

      /* 1. Grouping: show/hide headers, swap names */
      tbody.querySelectorAll(".dir-header").forEach(
        function(dh) {
          dh.style.display = grouped ? "" : "none";
          dh.classList.remove("collapsed");
        }
      );
      tbody.querySelectorAll(".dir-file").forEach(
        function(row) {
          var cell = row.children[0];
          var a = cell.querySelector("a");
          var name = cell.getAttribute("data-value");
          var base = name.replace(/.*\//, "");
          if (a) a.textContent = grouped ? base : name;
          else cell.textContent = grouped ? base : name;
          row.classList.toggle("dir-file-grouped", grouped);
          row.hidden = false;
          row.style.display = "";
        }
      );

      /* 2. Re-establish DOM order and sort */
      var sortIdx = -1;
      headers.forEach(function(h, i) {
        if (h.getAttribute("data-sort") === sortCol)
          sortIdx = i;
        h.classList.remove("sort-asc", "sort-desc");
      });

      function cmp(a, b) {
        if (sortIdx < 0) return 0;
        var av = a.children[sortIdx]
          .getAttribute("data-value");
        var bv = b.children[sortIdx]
          .getAttribute("data-value");
        var an = parseFloat(av);
        var bn = parseFloat(bv);
        var c = (isNaN(an) || isNaN(bn))
          ? (av || "").localeCompare(bv || "")
          : an - bn;
        return sortDir === "desc" ? -c : c;
      }

      if (sortIdx >= 0)
        headers[sortIdx].classList.add("sort-" + sortDir);

      if (grouped) {
        /* Move each file row after its dir-header */
        var dirMap = {};
        tbody.querySelectorAll(".dir-header").forEach(
          function(dh) {
            dirMap[dh.getAttribute("data-dir")] = dh;
          }
        );
        var files = Array.prototype.slice.call(
          tbody.querySelectorAll(".dir-file")
        );
        /* Group files by dir, sort within each group */
        var byDir = {};
        files.forEach(function(f) {
          var d = f.getAttribute("data-dir");
          if (!byDir[d]) byDir[d] = [];
          byDir[d].push(f);
        });
        Object.keys(dirMap).forEach(function(d) {
          var group = byDir[d] || [];
          group.sort(cmp);
          var dh = dirMap[d];
          var after = dh;
          group.forEach(function(f) {
            after.parentNode.insertBefore(f, after.nextSibling);
            after = f;
          });
        });
      } else {
        var all = Array.prototype.slice.call(
          tbody.querySelectorAll(".dir-file")
        );
        all.sort(cmp);
        all.forEach(function(r) { tbody.appendChild(r); });
      }

      /* 3. Filter */
      tbody.querySelectorAll(".dir-file").forEach(
        function(row) {
          var name = row.children[0]
            .getAttribute("data-value") || "";
          var cells = row.children;
          var tv = cells[cells.length - 2];
          var total = parseFloat(
            tv.getAttribute("data-value"));
          var show = (!re || re.test(name))
            && (!hide || total < 100);
          row.style.display = show ? "" : "none";
        }
      );

      /* Hide empty dir headers after filtering */
      if (grouped) {
        tbody.querySelectorAll(".dir-header").forEach(
          function(dh) {
            var hasVisible = false;
            var sib = dh.nextElementSibling;
            while (sib && sib.classList.contains("dir-file")) {
              if (sib.style.display !== "none")
                hasVisible = true;
              sib = sib.nextElementSibling;
            }
            dh.style.display = hasVisible ? "" : "none";
          }
        );
      }
    }

    /* Save state and re-render on changes */
    headers.forEach(function(h) {
      h.addEventListener("click", function() {
        var col = h.getAttribute("data-sort");
        if (sortCol === col) {
          sortDir = sortDir === "asc" ? "desc" : "asc";
        } else {
          sortCol = col;
          sortDir = "asc";
        }
        rset("sort-col", sortCol);
        rset("sort-dir", sortDir);
        render();
      });
    });

    if (filterInput) {
      filterInput.addEventListener("input", function() {
        rset("filter", filterInput.value);
        try {
          new RegExp(filterInput.value);
          filterInput.style.borderColor = "";
        } catch(e) {
          filterInput.style.borderColor =
            "var(--cov-none-border)";
        }
        render();
      });
    }

    if (hideCovered) {
      hideCovered.addEventListener("change", function() {
        rset("hide-covered", hideCovered.checked);
        render();
      });
    }

    if (groupToggle) {
      groupToggle.addEventListener("change", function() {
        rset("grouped", groupToggle.checked);
        render();
      });
    }

    /* Directory collapse/expand */
    tbody.addEventListener("click", function(e) {
      var dh = e.target.closest(".dir-header");
      if (!dh) return;
      var collapsed = dh.classList.toggle("collapsed");
      var sib = dh.nextElementSibling;
      while (sib && sib.classList.contains("dir-file")) {
        sib.hidden = collapsed;
        sib = sib.nextElementSibling;
      }
    });

    /* Initial render */
    render();
  }

  /* Truncated filename tooltip */
  var fileH1 = document.querySelector(".header h1");
  if (fileH1) {
    function updateH1Title() {
      if (fileH1.scrollWidth > fileH1.clientWidth)
        fileH1.title = fileH1.textContent.trim();
      else
        fileH1.removeAttribute("title");
    }
    updateH1Title();
    window.addEventListener("resize", updateH1Title);
  }

  /* Line detail expand/collapse (source view) */
  var sourceTable = document.querySelector(".source-table");
  if (sourceTable) {
    var details = sourceTable.querySelectorAll(".line-detail");
    details.forEach(function(d) { d.hidden = true; });

    function toggleDetail(row) {
      if (!row || !row.classList.contains("has-detail")) return;
      var d = row.nextElementSibling;
      if (!d || !d.classList.contains("line-detail")) return;
      d.hidden = !d.hidden;
      var ch = row.querySelector("td.chevron");
      if (ch) ch.textContent = d.hidden ? "\u25b6" : "\u25bc";
    }

    sourceTable.querySelectorAll(".has-detail").forEach(
      function(row) {
        row.addEventListener("click", function() {
          toggleDetail(row);
        });
      }
    );

    /* Badge criterion filter */
    var badges = document.querySelectorAll(
      ".header .stat-badge[data-criterion]");
    var activeCriterion = null;

    var detailIdx = -1;
    var currentRow = null;

    function clearFilter() {
      activeCriterion = null;
      detailIdx = -1;
      currentRow = null;
      details.forEach(function(d) { d.hidden = true; });
      sourceTable.querySelectorAll(".has-detail td.chevron")
        .forEach(function(ch) { ch.textContent = "\u25b6"; });
      badges.forEach(function(b) {
        b.classList.remove("badge-active");
      });
    }

    function applyFilter(crit) {
      activeCriterion = crit;
      badges.forEach(function(b) {
        b.classList.toggle("badge-active",
          b.getAttribute("data-criterion") === crit);
      });
      sourceTable.querySelectorAll(".has-detail").forEach(
        function(row) {
          var d = row.nextElementSibling;
          if (!d || !d.classList.contains("line-detail"))
            return;
          var errors = row.getAttribute("data-errors") || "";
          var match = errors.split(",").indexOf(crit) >= 0;
          d.hidden = !match;
          var ch = row.querySelector("td.chevron");
          if (ch) ch.textContent = match ? "\u25bc" : "\u25b6";
        }
      );
      detailIdx = 0;
      var first = sourceTable.querySelector(
        ".line-detail:not([hidden])");
      if (first) {
        currentRow = first.previousElementSibling || first;
        scrollHighlight(currentRow);
      }
    }

    function toggleFilter(crit) {
      if (crit === activeCriterion || crit === "statement") {
        clearFilter();
      } else {
        applyFilter(crit);
      }
    }

    badges.forEach(function(badge) {
      badge.addEventListener("click", function(e) {
        e.preventDefault();
        toggleFilter(badge.getAttribute("data-criterion"));
      });
    });

    /* Keyboard navigation */
    var uncovered = document.querySelectorAll(
      "tr[data-cov='0'], tr[data-cov='2']");
    var currentIdx = -1;

    function scrollHighlight(el) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      el.style.outline = "2px solid var(--link)";
      setTimeout(function() { el.style.outline = ""; }, 1500);
    }

    function openDetails() {
      var rows = [];
      sourceTable.querySelectorAll(".has-detail").forEach(
        function(row) {
          var d = row.nextElementSibling;
          if (d && d.classList.contains("line-detail") && !d.hidden)
            rows.push(row);
        }
      );
      return rows;
    }

    function jumpTo(idx) {
      if (idx < 0 || idx >= uncovered.length) return;
      currentIdx = idx;
      currentRow = uncovered[idx];
      scrollHighlight(currentRow);
    }

    var badgeKeys = {
      s: "statement", b: "branch", c: "condition",
      u: "subroutine", p: "pod"
    };

    document.addEventListener("keydown", function(e) {
      var tag = e.target.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA") return;
      if (e.key === "j" || e.key === "k") {
        if (activeCriterion) {
          var open = openDetails();
          if (!open.length) return;
          if (e.key === "j")
            detailIdx = (detailIdx + 1) % open.length;
          else
            detailIdx = (detailIdx - 1 + open.length) % open.length;
          currentRow = open[detailIdx];
          scrollHighlight(currentRow);
        } else {
          var len = uncovered.length;
          if (e.key === "j")
            jumpTo(currentIdx + 1 < len ? currentIdx + 1 : 0);
          else
            jumpTo(currentIdx > 0 ? currentIdx - 1 : len - 1);
        }
      }
      else if (badgeKeys[e.key]) {
        toggleFilter(badgeKeys[e.key]);
      }
      else if (e.key === "Enter" && currentRow) {
        toggleDetail(currentRow);
      }
      else if (e.key === "[") {
        var prev = document.querySelector(".nav-prev");
        if (prev) window.location = prev.href;
      }
      else if (e.key === "]") {
        var next = document.querySelector(".nav-next");
        if (next) window.location = next.href;
      }
    });

    /* Scroll minimap */
    var minimap = document.querySelector(".minimap");
    if (minimap) {
      var canvas = document.createElement("canvas");
      var allRows = sourceTable.querySelectorAll("tr[role='row']");
      var totalLines = allRows.length;
      canvas.width = 12;
      var mmHeight = function() {
        return minimap.clientHeight;
      };
      canvas.height = mmHeight();
      minimap.appendChild(canvas);
      var ctx = canvas.getContext("2d");
      var cs = getComputedStyle(document.documentElement);

      function gp(n) {
        return cs.getPropertyValue(n).trim();
      }

      function drawMinimap() {
        var h = canvas.height;
        ctx.clearRect(0, 0, 12, h);
        var scale = h / totalLines;
        for (var i = 0; i < totalLines; i++) {
          var cov = allRows[i].getAttribute("data-cov");
          if (cov === "0")
            ctx.fillStyle = gp("--cov-none-border");
          else if (cov === "2")
            ctx.fillStyle = gp("--cov-good-border");
          else if (cov === "1")
            ctx.fillStyle = gp("--cov-full-border");
          else continue;
          var y = Math.floor(i * scale);
          ctx.fillRect(0, y, 12, Math.max(1, Math.ceil(scale)));
        }
      }

      drawMinimap();
      window.addEventListener("resize", function() {
        canvas.height = mmHeight();
        drawMinimap();
      });

      canvas.addEventListener("click", function(e) {
        var lineIdx = Math.floor(e.offsetY / canvas.height * totalLines);
        if (lineIdx >= 0 && lineIdx < totalLines) {
          allRows[lineIdx].scrollIntoView({
            behavior: "smooth", block: "center"
          });
        }
      });
      canvas.style.cursor = "pointer";
    }
  }


})();
JS

"
And when he shall die,
Take him and cut him out in little stars,
And he will make the face of heaven so fine
That all the world will be in love with night
And pay no worship to the garish sun.
"

__END__

=encoding utf8

=head1 NAME

Devel::Cover::Report::Html_crisp - Modern HTML backend for Devel::Cover

=head1 SYNOPSIS

 cover -report html_crisp

=head1 DESCRIPTION

This module provides a modern HTML reporting mechanism for coverage data. It
generates a single-page dashboard with file listing and per-file source views
with inline branch, condition, and subroutine detail.

Features include dark mode support, keyboard navigation, sortable columns, and
inline condition truth tables.

It is designed to be called from the C<cover> program.  It will add syntax
highlighting if C<PPI::HTML> or C<Perl::Tidy> is installed.

=head1 OPTIONS

The following command line options are supported:

 -outputfile  - name of output file              (default coverage.html)
 -noppihtml   - disables PPI::HTML highlighting  (default off)
 -noperltidy  - disables Perl::Tidy highlighting (default off)

=head1 SEE ALSO

 Devel::Cover

=head1 LICENCE

Copyright 2026, Paul Johnson (paul@pjcj.net)

This software is free.  It is licensed under the same terms as Perl itself.

The latest version of this software should be available from my homepage:
https://pjcj.net

=cut
