#!/usr/bin/perl

# Copyright 2002-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

# Usage: create_gold [--test-output] [test ...]
#
# Creates golden results in test_output/cover/ for the given tests, or for
# every test in tests/ when none are named. With --test-output, writes each
# test's normalised cover output to <test>.out in the current directory
# instead, which make diff compares against the golden results.

use 5.20.0;
use warnings;

# VERSION

use feature "signatures";
no warnings "experimental::signatures";

use blib;
use FindBin ();
use lib "$FindBin::Bin/../t/lib";
use Config             qw( %Config );
use Devel::Cover::Test ();

sub get_tests_from_dir {
  my @tests;
  opendir my $dh, "tests" or die "Cannot opendir tests: $!";
  for my $t (sort readdir $dh) {
    next unless -f "tests/$t";
    next if $t =~ /\.(pm|pl|uncoverable|version|org|bak|swp)$/;
    next if $t =~ /~$/;
    push @tests, $t;
  }
  closedir $dh or die "Cannot closedir tests: $!";
  @tests
}

sub run_test_in_child ($test, $test_output) {
  my $e    = "t/e2e";
  my $file = (grep -e, "$e/$test", "$e/$test.t", "$e/a$test.t")[0] // $test;
  say $test_output
    ? "writing $test.out: "
    : "creating golden results for $test: ";
  my $pid = fork // die "Can't fork";
  if ($pid) {
    waitpid $pid, 0;
    my $status = $?;
    return 1 unless $status;
    my $reason
      = $status & 127
      ? "killed by signal " . ($status & 127)
      : "exited " . ($status >> 8);
    warn "$test failed: $reason\n";
    0
  } else {
    no warnings "redefine";
    local *Devel::Cover::Test::run_test = sub { };
    my $t = require "./$file" or die "Can't require $file: $!";
    ($test_output ? $t->create_out("$test.out") : $t->create_gold) and say "";
    exit;
  }
}

sub main {
  my $test_output = grep $_ eq "--test-output", @ARGV;
  my @tests       = grep $_ ne "--test-output", @ARGV;

  if (!$test_output && $Config{useithreads}) {
    say "useithreads true, no golden results written";
    return 0;
  }

  unless ($test_output) {
    mkdir "test_output"       unless -d "test_output";
    mkdir "test_output/cover" unless -d "test_output/cover";
  }

  @tests = get_tests_from_dir unless @tests;
  my @failed = grep !run_test_in_child($_, $test_output), @tests;
  if (@failed) {
    warn "Failed: @failed\n";
    return @failed > 255 ? 255 : scalar @failed;
  }
  0
}

exit main
