#!/usr/bin/perl

# Copyright 2011-2012, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

require 5.6.1;

use strict;
use warnings;

# VERSION

my @tests = @ARGV;
die "Only one test allowed" if @tests > 1;
my $fn = @tests ? $tests[0] : "";
unlink for <test_output/cover/$fn*>;
exec $^X, "utils/all_versions", "make", "gold", "TEST=@tests"
