#!/usr/bin/perl

# Copyright 2011-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use 5.20.0;
use warnings;

# VERSION

my @Tests = @ARGV;
die "Only one test allowed" if @Tests > 1;
my $Fn = @Tests ? $Tests[0] : "";
unlink for <test_output/cover/$Fn.*>;
# print "tests [@Tests]\n";
exec $^X, "utils/all_versions", "make", "gold", "TEST=@Tests"
