#!/usr/bin/perl

# Copyright 2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

require 5.6.1;

use strict;
use warnings;

# VERSION

use File::Path;

use Config;
exit if $Config{useithreads};

my @tests = @ARGV;
die "Only one test allowed" if @tests > 1;
rmtree "test_output" unless @tests;
exec $^X, "utils/all_versions", "make", "gold", "TEST=@tests"
