#!/bin/sh -x

JOBS=16
export PATH=$PERLBREW_ROOT/perls/cpancover/bin:$PATH
rm -rf ~/.cpanm
rm -rf ~/cpancover
cpan App::cpanminus
cpanm -nf .
cpanm -nf App::cpanoutdated
cpan-outdated | cpanm -nf
perl -Mblib bin/cpancover -force -verbose -results_dir ~/cpancover \
                          -workers $JOBS -module_file utils/cpancover_modules
find ~/cpancover -type f -exec gzip -9 {} \;
chmod -R o=g ~/cpancover
www=/usr/share/nginx/www
new=$www/`date +%F`
sudo mv $new $new.$$
sudo cp -a ~/cpancover $new
sudo rm $www/latest
sudo ln -s $new $www/latest
