#!/usr/bin/perl

# Copyright 2006-2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use 5.20.0;
use warnings;
use feature qw( postderef signatures );
no warnings qw( experimental::postderef experimental::signatures );

use Digest::MD5 ();

process_file($_) for @ARGV;

sub process_file ($file) {
  open my $fh, "<", $file or die "Can't open $file: $!\n";
  while (my $line = <$fh>) {
    my ($count, $crit, $reason)
      = $line =~ m/# uncoverable:\s+(\d+)\s+(\w+)\s+(.*$)/
      or next;
    my $md5 = Digest::MD5->new->add($line)->hexdigest;
    $crit =~ s/s$//;
    for (0 .. $count - 1) {
      print "$file $crit $md5 $_ 0 $reason\n";
    }
  }
}
