#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use 5.20.0;
use warnings;
use feature qw( postderef say signatures );
no warnings qw( experimental::postderef experimental::signatures );

use Cwd        qw( realpath );
use File::Path qw( remove_tree );
use File::Spec ();
use FindBin    ();

use lib "$FindBin::Bin/../t/lib", qw( ./lib ./blib/lib ./blib/arch );

use Devel::Cover::Test::Showcase qw(
  create_cover_db
  run_cover
  setup_lib_dir
);

my $Base = File::Spec->catdir(realpath(File::Spec->tmpdir), "dc-showcase");

sub launch ($path) {
  system("open", $path) == 0 or system "xdg-open", $path
}

sub main (@args) {
  my $report = $args[0] // die "Usage: $0 <report-name>\n";

  remove_tree($Base) if -d $Base;
  local $ENV{TMPDIR} = $Base;
  mkdir $Base or die "Cannot create $Base: $!\n";

  say "Setting up fixture modules";
  my ($tmpdir, $libdir) = setup_lib_dir;

  say "Collecting coverage";
  my $cover_db = create_cover_db($tmpdir, $libdir);

  say "Generating $report report";
  my $outdir = File::Spec->catdir($Base, $report);

  my ($out, $exit) = run_cover(
    "--select_dir", $libdir, "--outputdir", $outdir,
    "--report",     $report, "--silent",    $cover_db,
  );
  print $out;
  die "cover failed (exit $exit)\n" if $exit;

  my $index = File::Spec->catfile($outdir, "coverage.html");
  if (-f $index) {
    say "Report: $index";
    launch($index);
  } elsif (-d $outdir) {
    opendir my $dh, $outdir or return;
    my @files = sort grep !/^\.|\.lock$/, readdir $dh;
    closedir $dh;
    say "Report: " . File::Spec->catfile($outdir, $_) for @files;
  }
}

main @ARGV;

__END__

=encoding utf8

=head1 NAME

showcase - generate a Devel::Cover report from fixture modules

=head1 SYNOPSIS

 perl utils/showcase text
 perl utils/showcase html_crisp

 # Or via make targets:
 make showcase_text
 make showcase_html_crisp

=head1 DESCRIPTION

Generate a Devel::Cover report using the fixture modules from
L<Devel::Cover::Test::Showcase>.  Four modules under C<Covered::> are exercised
with representative calls; four identical modules under C<Uncovered::> are
included via C<--select_dir> but never loaded, so they appear as untested files
in the report.

File-writing reports (HTML, JSON variants) write their output to a per-report
subdirectory under C</tmp/dc-showcase/>.  HTML reports are also opened in the
default browser.

=head1 ARGUMENTS

A single required argument: the report format name.  This is passed directly to
C<cover --report>, e.g. C<text>, C<html_crisp>, C<html_basic>, C<compilation>.

=head1 SEE ALSO

L<Devel::Cover::Test::Showcase>, L<Devel::Cover>

=head1 LICENCE

Copyright 2026, Paul Johnson (paul@pjcj.net)

This software is free.  It is licensed under the same terms as Perl itself.

The latest version of this software should be available from my homepage:
https://pjcj.net

=cut
