#!/usr/bin/perl

# Copyright 2026, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# https://pjcj.net

use 5.20.0;
use warnings;
use feature qw( postderef signatures );
no warnings qw( experimental::postderef experimental::signatures );

use FindBin ();
use lib "$FindBin::Bin/../lib", $FindBin::Bin,
  qw( ./lib ./blib/lib ./blib/arch );

use Cwd        qw( realpath );
use File::Path qw( make_path );
use File::Spec ();
use File::Temp qw( tempdir );
use Test::More import => [qw( diag done_testing is like ok )];

use Devel::Cover::Inc            ();
use Devel::Cover::Test::Showcase qw( run_cover slurp );

# A dev build still has the bare dzil marker line in its sources - a
# released dist has it expanded to a $VERSION assignment. This gives the
# test an oracle independent of the Makefile.PL detection it verifies.
sub expected_suffix () {
  slurp("lib/Devel/Cover.pm") =~ /^\s*# VERSION$/m ? "+" : ""
}

sub setup_db () {
  my $tmpdir = realpath(tempdir(CLEANUP => 1));
  my $libdir = File::Spec->catdir($tmpdir, "lib");
  make_path($libdir);

  my $module = File::Spec->catfile($libdir, "Foo.pm");
  open my $fh, ">", $module or die "Cannot write $module: $!";
  print $fh "package Foo;\nsub hi { 1 }\n1;\n";
  close $fh or die "Cannot close $module: $!";

  my $cover_db = File::Spec->catdir($tmpdir, "cover_db");
  local $ENV{DEVEL_COVER_SELF};
  delete $ENV{DEVEL_COVER_SELF};
  my $cmd
    = "$^X -Iblib/lib -Iblib/arch -I$libdir"
    . " -MDevel::Cover=-db,$cover_db,-silent,1,-merge,0,-select,Foo"
    . ' -e "use Foo; Foo::hi()" 2>&1';
  my $out = `$cmd`;
  die "Failed to create cover_db:\n$out\n" if $?;

  ($tmpdir, $cover_db)
}

sub main () {
  my $suffix  = expected_suffix;
  my $display = $Devel::Cover::Inc::VERSION . $suffix;

  is $Devel::Cover::Inc::Dev, $suffix,
    "Inc records the dev suffix (" . ($suffix || "release") . ")";

  my ($out) = run_cover("-v");
  like $out, qr/version \Q$display\E$/m, "cover -v shows the suffix";

  my $have_template = eval "require Template; 1";
  my ($tmpdir, $cover_db) = setup_db;

  for my $report (qw( html_crisp html_basic html_subtle html_minimal vim )) {
    next if $report =~ /^html_(basic|subtle)$/ && !$have_template;

    my $outdir = File::Spec->catdir($tmpdir, $report);
    my ($rout, $exit) = run_cover(
      "--report", $report, "--outputdir", $outdir, "--silent", $cover_db,
    );
    is $exit, 0, "$report: cover exits 0" or diag $rout;

    my @pages
      = $report eq "vim" ? ("$outdir/coverage.vim") : glob "$outdir/*.html";
    ok(
      (
        grep { slurp($_) =~ /generated by Devel::Cover Version \Q$display\E$/m }
          @pages
      ),
      "$report: generated-by comment shows the version with suffix",
    );

    if ($report eq "html_crisp") {
      like slurp("$outdir/coverage.html"),
        qr/Devel::Cover<\/a>\s+\Q$display\E\s+by/,
        "crisp footer shows the version with suffix";
    }
  }

  done_testing;
}

main;
